using System.Management.Automation;

namespace Cohesity.Powershell.Cmdlets.ProtectionJob
{
    /// <summary>
    /// <para type="synopsis">
    /// Removes a Protection Job.
    /// </para>
    /// <para type="description">
    /// Returns Success if the Protection Job is deleted.
    /// </para>
    /// </summary>
    /// <example>
    ///   <para>PS&gt;</para>
    ///   <code>
    ///   Remove-CohesityProtectionJob -Id 1234
    ///   </code>
    ///   <para>
    ///   Removes a Protection Job with the Id of 1234 and all Snapshots generated by the Protection Job.
    ///   </para>
    /// </example>
    /// <example>
    ///   <para>PS&gt;</para>
    ///   <code>
    ///   Remove-CohesityProtectionJob -Id 1234 -DeleteSnapshots false
    ///   </code>
    ///   <para>
    ///   Removes a Protection Job with the Id of 1234 only, Snapshots generated by the Protection Job will not be deleted.
    ///   </para>
    /// </example>
    [Cmdlet(VerbsCommon.Remove, "CohesityProtectionJob")]
    public class RemoveCohesityProtectionJob : PSCmdlet
    {
        private Session Session
        {
            get
            {
                var result = SessionState.PSVariable.GetValue("Session") as Session;
                if (result == null)
                {
                    result = new Session();
                    SessionState.PSVariable.Set("Session", result);
                }
                return result;
            }
        }

        #region Params

        /// <summary>
        /// <para type="description">
        /// Specifies the unique id of the Protection Job.
        /// </para>
        /// </summary>
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true)]
        [ValidateRange(1, long.MaxValue)]
        public long Id { get; set; }

        /// <summary>
        /// <para type="description">
        /// Specifies if Snapshots generated by the Protection Job should also be deleted when the Job is deleted.
        /// Default value is true.
        /// </para>
        /// </summary>
        [Parameter(Mandatory = false)]
        public bool DeleteSnapshots { get; set; } = true;

        #endregion

        #region Processing

        /// <summary>
        /// Preprocess
        /// </summary>
        protected override void BeginProcessing()
        {
            base.BeginProcessing();

            Session.AssertAuthentication();
        }

        /// <summary>
        /// Process
        /// </summary>
        protected override void ProcessRecord()
        {
            // POST /public/protectionJobState/{id}
            var content = new {
                DeleteSnapshots
            };

            var preparedUrl = $"/public/protectionJobs/{Id.ToString()}";
            Session.NetworkClient.Delete(preparedUrl, content);
            WriteObject("Protection job was deleted successfully.");
        }

        #endregion
    }
}
