/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CertificatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CertificatesApiTests
    {
        private CertificatesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CertificatesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CertificatesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CertificatesApi
            //Assert.IsInstanceOfType(typeof(CertificatesApi), instance, "instance is a CertificatesApi");
        }

        
        /// <summary>
        /// Test DeleteWebServerCertificate
        /// </summary>
        [Test]
        public void DeleteWebServerCertificateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DeleteWebServerCertificate();
            
        }
        
        /// <summary>
        /// Test GetWebServerCertificate
        /// </summary>
        [Test]
        public void GetWebServerCertificateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetWebServerCertificate();
            //Assert.IsInstanceOf<SslCertificateConfig> (response, "response is SslCertificateConfig");
        }
        
        /// <summary>
        /// Test UpdateWebServerCertificate
        /// </summary>
        [Test]
        public void UpdateWebServerCertificateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SslCertificateConfig body = null;
            //var response = instance.UpdateWebServerCertificate(body);
            //Assert.IsInstanceOf<SslCertificateConfig> (response, "response is SslCertificateConfig");
        }
        
    }

}
