/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ClusterPartitionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ClusterPartitionsApiTests
    {
        private ClusterPartitionsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ClusterPartitionsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClusterPartitionsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ClusterPartitionsApi
            //Assert.IsInstanceOfType(typeof(ClusterPartitionsApi), instance, "instance is a ClusterPartitionsApi");
        }

        
        /// <summary>
        /// Test GetClusterPartitionById
        /// </summary>
        [Test]
        public void GetClusterPartitionByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetClusterPartitionById(id);
            //Assert.IsInstanceOf<ClusterPartition> (response, "response is ClusterPartition");
        }
        
        /// <summary>
        /// Test GetClusterPartitions
        /// </summary>
        [Test]
        public void GetClusterPartitionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long?> ids = null;
            //List<string> names = null;
            //var response = instance.GetClusterPartitions(ids, names);
            //Assert.IsInstanceOf<List<ClusterPartition>> (response, "response is List<ClusterPartition>");
        }
        
    }

}
