/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DashboardApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DashboardApiTests
    {
        private DashboardApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DashboardApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DashboardApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DashboardApi
            //Assert.IsInstanceOfType(typeof(DashboardApi), instance, "instance is a DashboardApi");
        }

        
        /// <summary>
        /// Test GetDashboard
        /// </summary>
        [Test]
        public void GetDashboardTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? clusterId = null;
            //bool? allClusters = null;
            //var response = instance.GetDashboard(clusterId, allClusters);
            //Assert.IsInstanceOf<DashboardResponse> (response, "response is DashboardResponse");
        }
        
    }

}
