/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SchedulerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SchedulerApiTests
    {
        private SchedulerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SchedulerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchedulerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SchedulerApi
            //Assert.IsInstanceOfType(typeof(SchedulerApi), instance, "instance is a SchedulerApi");
        }

        
        /// <summary>
        /// Test CreateSchedulerJob
        /// </summary>
        [Test]
        public void CreateSchedulerJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SchedulerProtoSchedulerJob body = null;
            //var response = instance.CreateSchedulerJob(body);
            //Assert.IsInstanceOf<SchedulerProtoSchedulerJobScheduleJobParametersReportJobParameter> (response, "response is SchedulerProtoSchedulerJobScheduleJobParametersReportJobParameter");
        }
        
        /// <summary>
        /// Test DeleteSchedulerJobs
        /// </summary>
        [Test]
        public void DeleteSchedulerJobsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long?> ids = null;
            //instance.DeleteSchedulerJobs(ids);
            
        }
        
        /// <summary>
        /// Test GetSchedulerJobs
        /// </summary>
        [Test]
        public void GetSchedulerJobsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSchedulerJobs();
            //Assert.IsInstanceOf<SchedulerProto> (response, "response is SchedulerProto");
        }
        
        /// <summary>
        /// Test UpdateSchedulerJob
        /// </summary>
        [Test]
        public void UpdateSchedulerJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SchedulerProtoSchedulerJob body = null;
            //var response = instance.UpdateSchedulerJob(body);
            //Assert.IsInstanceOf<SchedulerProtoSchedulerJob> (response, "response is SchedulerProtoSchedulerJob");
        }
        
    }

}
