/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ViewBoxesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ViewBoxesApiTests
    {
        private ViewBoxesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ViewBoxesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ViewBoxesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ViewBoxesApi
            //Assert.IsInstanceOfType(typeof(ViewBoxesApi), instance, "instance is a ViewBoxesApi");
        }

        
        /// <summary>
        /// Test CreateViewBox
        /// </summary>
        [Test]
        public void CreateViewBoxTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateViewBoxParams body = null;
            //var response = instance.CreateViewBox(body);
            //Assert.IsInstanceOf<ViewBox> (response, "response is ViewBox");
        }
        
        /// <summary>
        /// Test GetViewBoxById
        /// </summary>
        [Test]
        public void GetViewBoxByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetViewBoxById(id);
            //Assert.IsInstanceOf<ViewBox> (response, "response is ViewBox");
        }
        
        /// <summary>
        /// Test GetViewBoxes
        /// </summary>
        [Test]
        public void GetViewBoxesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long?> ids = null;
            //List<string> names = null;
            //List<long?> clusterPartitionIds = null;
            //bool? fetchStats = null;
            //var response = instance.GetViewBoxes(ids, names, clusterPartitionIds, fetchStats);
            //Assert.IsInstanceOf<List<ViewBox>> (response, "response is List<ViewBox>");
        }
        
        /// <summary>
        /// Test UpdateViewBox
        /// </summary>
        [Test]
        public void UpdateViewBoxTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //CreateViewBoxParams body = null;
            //var response = instance.UpdateViewBox(id, body);
            //Assert.IsInstanceOf<ViewBox> (response, "response is ViewBox");
        }
        
    }

}
