/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VlanApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class VlanApiTests
    {
        private VlanApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new VlanApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VlanApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VlanApi
            //Assert.IsInstanceOfType(typeof(VlanApi), instance, "instance is a VlanApi");
        }

        
        /// <summary>
        /// Test GetVlanById
        /// </summary>
        [Test]
        public void GetVlanByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.GetVlanById(id);
            //Assert.IsInstanceOf<Vlan> (response, "response is Vlan");
        }
        
        /// <summary>
        /// Test GetVlans
        /// </summary>
        [Test]
        public void GetVlansTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetVlans();
            //Assert.IsInstanceOf<List<Vlan>> (response, "response is List<Vlan>");
        }
        
        /// <summary>
        /// Test RemoveVlan
        /// </summary>
        [Test]
        public void RemoveVlanTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.RemoveVlan(id);
            
        }
        
        /// <summary>
        /// Test UpdateVlan
        /// </summary>
        [Test]
        public void UpdateVlanTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //Vlan body = null;
            //var response = instance.UpdateVlan(id, body);
            //Assert.IsInstanceOf<Vlan> (response, "response is Vlan");
        }
        
    }

}
