/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccessToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccessTokenTests
    {
        // TODO uncomment below to declare an instance variable for AccessToken
        //private AccessToken instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccessToken
            //instance = new AccessToken();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccessToken
        /// </summary>
        [Test]
        public void AccessTokenInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccessToken
            //Assert.IsInstanceOfType<AccessToken> (instance, "variable 'instance' is a AccessToken");
        }


        /// <summary>
        /// Test the property '_AccessToken'
        /// </summary>
        [Test]
        public void _AccessTokenTest()
        {
            // TODO unit test for the property '_AccessToken'
        }
        /// <summary>
        /// Test the property 'Privileges'
        /// </summary>
        [Test]
        public void PrivilegesTest()
        {
            // TODO unit test for the property 'Privileges'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Test]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }

    }

}
