/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AddedActiveDirectoryPrincipal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddedActiveDirectoryPrincipalTests
    {
        // TODO uncomment below to declare an instance variable for AddedActiveDirectoryPrincipal
        //private AddedActiveDirectoryPrincipal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddedActiveDirectoryPrincipal
            //instance = new AddedActiveDirectoryPrincipal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddedActiveDirectoryPrincipal
        /// </summary>
        [Test]
        public void AddedActiveDirectoryPrincipalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddedActiveDirectoryPrincipal
            //Assert.IsInstanceOfType<AddedActiveDirectoryPrincipal> (instance, "variable 'instance' is a AddedActiveDirectoryPrincipal");
        }


        /// <summary>
        /// Test the property 'CreatedTimeMsecs'
        /// </summary>
        [Test]
        public void CreatedTimeMsecsTest()
        {
            // TODO unit test for the property 'CreatedTimeMsecs'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'LastUpdatedTimeMsecs'
        /// </summary>
        [Test]
        public void LastUpdatedTimeMsecsTest()
        {
            // TODO unit test for the property 'LastUpdatedTimeMsecs'
        }
        /// <summary>
        /// Test the property 'ObjectClass'
        /// </summary>
        [Test]
        public void ObjectClassTest()
        {
            // TODO unit test for the property 'ObjectClass'
        }
        /// <summary>
        /// Test the property 'PrincipalName'
        /// </summary>
        [Test]
        public void PrincipalNameTest()
        {
            // TODO unit test for the property 'PrincipalName'
        }
        /// <summary>
        /// Test the property 'Restricted'
        /// </summary>
        [Test]
        public void RestrictedTest()
        {
            // TODO unit test for the property 'Restricted'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Test]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'Sid'
        /// </summary>
        [Test]
        public void SidTest()
        {
            // TODO unit test for the property 'Sid'
        }

    }

}
