/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AggregatedSubtreeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AggregatedSubtreeInfoTests
    {
        // TODO uncomment below to declare an instance variable for AggregatedSubtreeInfo
        //private AggregatedSubtreeInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AggregatedSubtreeInfo
            //instance = new AggregatedSubtreeInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AggregatedSubtreeInfo
        /// </summary>
        [Test]
        public void AggregatedSubtreeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AggregatedSubtreeInfo
            //Assert.IsInstanceOfType<AggregatedSubtreeInfo> (instance, "variable 'instance' is a AggregatedSubtreeInfo");
        }


        /// <summary>
        /// Test the property 'Environment'
        /// </summary>
        [Test]
        public void EnvironmentTest()
        {
            // TODO unit test for the property 'Environment'
        }
        /// <summary>
        /// Test the property 'LeavesCount'
        /// </summary>
        [Test]
        public void LeavesCountTest()
        {
            // TODO unit test for the property 'LeavesCount'
        }
        /// <summary>
        /// Test the property 'TotalLogicalSize'
        /// </summary>
        [Test]
        public void TotalLogicalSizeTest()
        {
            // TODO unit test for the property 'TotalLogicalSize'
        }

    }

}
