/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AppRunHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppRunHistoryTests
    {
        // TODO uncomment below to declare an instance variable for AppRunHistory
        //private AppRunHistory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppRunHistory
            //instance = new AppRunHistory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppRunHistory
        /// </summary>
        [Test]
        public void AppRunHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppRunHistory
            //Assert.IsInstanceOfType<AppRunHistory> (instance, "variable 'instance' is a AppRunHistory");
        }


        /// <summary>
        /// Test the property 'AppInfo'
        /// </summary>
        [Test]
        public void AppInfoTest()
        {
            // TODO unit test for the property 'AppInfo'
        }
        /// <summary>
        /// Test the property 'MrInstances'
        /// </summary>
        [Test]
        public void MrInstancesTest()
        {
            // TODO unit test for the property 'MrInstances'
        }

    }

}
