/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ArchivalTarget1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ArchivalTarget1Tests
    {
        // TODO uncomment below to declare an instance variable for ArchivalTarget1
        //private ArchivalTarget1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ArchivalTarget1
            //instance = new ArchivalTarget1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ArchivalTarget1
        /// </summary>
        [Test]
        public void ArchivalTarget1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ArchivalTarget1
            //Assert.IsInstanceOfType<ArchivalTarget1> (instance, "variable 'instance' is a ArchivalTarget1");
        }


        /// <summary>
        /// Test the property 'VaultId'
        /// </summary>
        [Test]
        public void VaultIdTest()
        {
            // TODO unit test for the property 'VaultId'
        }
        /// <summary>
        /// Test the property 'VaultName'
        /// </summary>
        [Test]
        public void VaultNameTest()
        {
            // TODO unit test for the property 'VaultName'
        }
        /// <summary>
        /// Test the property 'VaultType'
        /// </summary>
        [Test]
        public void VaultTypeTest()
        {
            // TODO unit test for the property 'VaultType'
        }

    }

}
