/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChassisInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChassisInfoTests
    {
        // TODO uncomment below to declare an instance variable for ChassisInfo
        //private ChassisInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChassisInfo
            //instance = new ChassisInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChassisInfo
        /// </summary>
        [Test]
        public void ChassisInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChassisInfo
            //Assert.IsInstanceOfType<ChassisInfo> (instance, "variable 'instance' is a ChassisInfo");
        }


        /// <summary>
        /// Test the property 'ChassisId'
        /// </summary>
        [Test]
        public void ChassisIdTest()
        {
            // TODO unit test for the property 'ChassisId'
        }
        /// <summary>
        /// Test the property 'ChassisName'
        /// </summary>
        [Test]
        public void ChassisNameTest()
        {
            // TODO unit test for the property 'ChassisName'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'RackId'
        /// </summary>
        [Test]
        public void RackIdTest()
        {
            // TODO unit test for the property 'RackId'
        }

    }

}
