/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DataTransferFromVaultsSummaryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataTransferFromVaultsSummaryResponseTests
    {
        // TODO uncomment below to declare an instance variable for DataTransferFromVaultsSummaryResponse
        //private DataTransferFromVaultsSummaryResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataTransferFromVaultsSummaryResponse
            //instance = new DataTransferFromVaultsSummaryResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataTransferFromVaultsSummaryResponse
        /// </summary>
        [Test]
        public void DataTransferFromVaultsSummaryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataTransferFromVaultsSummaryResponse
            //Assert.IsInstanceOfType<DataTransferFromVaultsSummaryResponse> (instance, "variable 'instance' is a DataTransferFromVaultsSummaryResponse");
        }


        /// <summary>
        /// Test the property 'DataTransferSummary'
        /// </summary>
        [Test]
        public void DataTransferSummaryTest()
        {
            // TODO unit test for the property 'DataTransferSummary'
        }

    }

}
