/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EntitySchemaProto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntitySchemaProtoTests
    {
        // TODO uncomment below to declare an instance variable for EntitySchemaProto
        //private EntitySchemaProto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EntitySchemaProto
            //instance = new EntitySchemaProto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntitySchemaProto
        /// </summary>
        [Test]
        public void EntitySchemaProtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EntitySchemaProto
            //Assert.IsInstanceOfType<EntitySchemaProto> (instance, "variable 'instance' is a EntitySchemaProto");
        }


        /// <summary>
        /// Test the property 'AttributesDescriptor'
        /// </summary>
        [Test]
        public void AttributesDescriptorTest()
        {
            // TODO unit test for the property 'AttributesDescriptor'
        }
        /// <summary>
        /// Test the property 'IsInternalSchema'
        /// </summary>
        [Test]
        public void IsInternalSchemaTest()
        {
            // TODO unit test for the property 'IsInternalSchema'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SchemaDescriptiveName'
        /// </summary>
        [Test]
        public void SchemaDescriptiveNameTest()
        {
            // TODO unit test for the property 'SchemaDescriptiveName'
        }
        /// <summary>
        /// Test the property 'SchemaHelpText'
        /// </summary>
        [Test]
        public void SchemaHelpTextTest()
        {
            // TODO unit test for the property 'SchemaHelpText'
        }
        /// <summary>
        /// Test the property 'TimeSeriesDescriptorVec'
        /// </summary>
        [Test]
        public void TimeSeriesDescriptorVecTest()
        {
            // TODO unit test for the property 'TimeSeriesDescriptorVec'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
