/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EntitySchemaProtoAttributesDescriptor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntitySchemaProtoAttributesDescriptorTests
    {
        // TODO uncomment below to declare an instance variable for EntitySchemaProtoAttributesDescriptor
        //private EntitySchemaProtoAttributesDescriptor instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EntitySchemaProtoAttributesDescriptor
            //instance = new EntitySchemaProtoAttributesDescriptor();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntitySchemaProtoAttributesDescriptor
        /// </summary>
        [Test]
        public void EntitySchemaProtoAttributesDescriptorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EntitySchemaProtoAttributesDescriptor
            //Assert.IsInstanceOfType<EntitySchemaProtoAttributesDescriptor> (instance, "variable 'instance' is a EntitySchemaProtoAttributesDescriptor");
        }


        /// <summary>
        /// Test the property 'AttributeVec'
        /// </summary>
        [Test]
        public void AttributeVecTest()
        {
            // TODO unit test for the property 'AttributeVec'
        }
        /// <summary>
        /// Test the property 'KeyAttributeNameIndex'
        /// </summary>
        [Test]
        public void KeyAttributeNameIndexTest()
        {
            // TODO unit test for the property 'KeyAttributeNameIndex'
        }

    }

}
