/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FileRestoreInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileRestoreInfoTests
    {
        // TODO uncomment below to declare an instance variable for FileRestoreInfo
        //private FileRestoreInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileRestoreInfo
            //instance = new FileRestoreInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileRestoreInfo
        /// </summary>
        [Test]
        public void FileRestoreInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileRestoreInfo
            //Assert.IsInstanceOfType<FileRestoreInfo> (instance, "variable 'instance' is a FileRestoreInfo");
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'FilesystemVolume'
        /// </summary>
        [Test]
        public void FilesystemVolumeTest()
        {
            // TODO unit test for the property 'FilesystemVolume'
        }
        /// <summary>
        /// Test the property 'IsFolder'
        /// </summary>
        [Test]
        public void IsFolderTest()
        {
            // TODO unit test for the property 'IsFolder'
        }

    }

}
