/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FullNoCBTScript_
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FullNoCBTScript_Tests
    {
        // TODO uncomment below to declare an instance variable for FullNoCBTScript_
        //private FullNoCBTScript_ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FullNoCBTScript_
            //instance = new FullNoCBTScript_();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FullNoCBTScript_
        /// </summary>
        [Test]
        public void FullNoCBTScript_InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FullNoCBTScript_
            //Assert.IsInstanceOfType<FullNoCBTScript_> (instance, "variable 'instance' is a FullNoCBTScript_");
        }


        /// <summary>
        /// Test the property 'ScriptParams'
        /// </summary>
        [Test]
        public void ScriptParamsTest()
        {
            // TODO unit test for the property 'ScriptParams'
        }
        /// <summary>
        /// Test the property 'ScriptPath'
        /// </summary>
        [Test]
        public void ScriptPathTest()
        {
            // TODO unit test for the property 'ScriptPath'
        }

    }

}
