/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IndexAndSnapshots
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IndexAndSnapshotsTests
    {
        // TODO uncomment below to declare an instance variable for IndexAndSnapshots
        //private IndexAndSnapshots instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IndexAndSnapshots
            //instance = new IndexAndSnapshots();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IndexAndSnapshots
        /// </summary>
        [Test]
        public void IndexAndSnapshotsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IndexAndSnapshots
            //Assert.IsInstanceOfType<IndexAndSnapshots> (instance, "variable 'instance' is a IndexAndSnapshots");
        }


        /// <summary>
        /// Test the property 'ArchiveTaskUid'
        /// </summary>
        [Test]
        public void ArchiveTaskUidTest()
        {
            // TODO unit test for the property 'ArchiveTaskUid'
        }
        /// <summary>
        /// Test the property 'EndTimeUsecs'
        /// </summary>
        [Test]
        public void EndTimeUsecsTest()
        {
            // TODO unit test for the property 'EndTimeUsecs'
        }
        /// <summary>
        /// Test the property 'RemoteProtectionJobUid'
        /// </summary>
        [Test]
        public void RemoteProtectionJobUidTest()
        {
            // TODO unit test for the property 'RemoteProtectionJobUid'
        }
        /// <summary>
        /// Test the property 'StartTimeUsecs'
        /// </summary>
        [Test]
        public void StartTimeUsecsTest()
        {
            // TODO unit test for the property 'StartTimeUsecs'
        }
        /// <summary>
        /// Test the property 'ViewBoxId'
        /// </summary>
        [Test]
        public void ViewBoxIdTest()
        {
            // TODO unit test for the property 'ViewBoxId'
        }

    }

}
