/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JobRunsTile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JobRunsTileTests
    {
        // TODO uncomment below to declare an instance variable for JobRunsTile
        //private JobRunsTile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JobRunsTile
            //instance = new JobRunsTile();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JobRunsTile
        /// </summary>
        [Test]
        public void JobRunsTileInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JobRunsTile
            //Assert.IsInstanceOfType<JobRunsTile> (instance, "variable 'instance' is a JobRunsTile");
        }


        /// <summary>
        /// Test the property 'ObjectsProtectedByPolicy'
        /// </summary>
        [Test]
        public void ObjectsProtectedByPolicyTest()
        {
            // TODO unit test for the property 'ObjectsProtectedByPolicy'
        }
        /// <summary>
        /// Test the property 'LastDayNumJobErrors'
        /// </summary>
        [Test]
        public void LastDayNumJobErrorsTest()
        {
            // TODO unit test for the property 'LastDayNumJobErrors'
        }
        /// <summary>
        /// Test the property 'LastDayNumJobRuns'
        /// </summary>
        [Test]
        public void LastDayNumJobRunsTest()
        {
            // TODO unit test for the property 'LastDayNumJobRuns'
        }
        /// <summary>
        /// Test the property 'LastDayNumJobSlaViolations'
        /// </summary>
        [Test]
        public void LastDayNumJobSlaViolationsTest()
        {
            // TODO unit test for the property 'LastDayNumJobSlaViolations'
        }
        /// <summary>
        /// Test the property 'NumJobRunning'
        /// </summary>
        [Test]
        public void NumJobRunningTest()
        {
            // TODO unit test for the property 'NumJobRunning'
        }

    }

}
