/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LocalStatistics_
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LocalStatistics_Tests
    {
        // TODO uncomment below to declare an instance variable for LocalStatistics_
        //private LocalStatistics_ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LocalStatistics_
            //instance = new LocalStatistics_();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LocalStatistics_
        /// </summary>
        [Test]
        public void LocalStatistics_InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalStatistics_
            //Assert.IsInstanceOfType<LocalStatistics_> (instance, "variable 'instance' is a LocalStatistics_");
        }


        /// <summary>
        /// Test the property 'DataInBytes'
        /// </summary>
        [Test]
        public void DataInBytesTest()
        {
            // TODO unit test for the property 'DataInBytes'
        }
        /// <summary>
        /// Test the property 'DataInBytesAfterReduction'
        /// </summary>
        [Test]
        public void DataInBytesAfterReductionTest()
        {
            // TODO unit test for the property 'DataInBytesAfterReduction'
        }
        /// <summary>
        /// Test the property 'MinUsablePhysicalCapacityBytes'
        /// </summary>
        [Test]
        public void MinUsablePhysicalCapacityBytesTest()
        {
            // TODO unit test for the property 'MinUsablePhysicalCapacityBytes'
        }
        /// <summary>
        /// Test the property 'NumBytesRead'
        /// </summary>
        [Test]
        public void NumBytesReadTest()
        {
            // TODO unit test for the property 'NumBytesRead'
        }
        /// <summary>
        /// Test the property 'NumBytesWritten'
        /// </summary>
        [Test]
        public void NumBytesWrittenTest()
        {
            // TODO unit test for the property 'NumBytesWritten'
        }
        /// <summary>
        /// Test the property 'PhysicalCapacityBytes'
        /// </summary>
        [Test]
        public void PhysicalCapacityBytesTest()
        {
            // TODO unit test for the property 'PhysicalCapacityBytes'
        }
        /// <summary>
        /// Test the property 'ReadIos'
        /// </summary>
        [Test]
        public void ReadIosTest()
        {
            // TODO unit test for the property 'ReadIos'
        }
        /// <summary>
        /// Test the property 'ReadLatencyMsecs'
        /// </summary>
        [Test]
        public void ReadLatencyMsecsTest()
        {
            // TODO unit test for the property 'ReadLatencyMsecs'
        }
        /// <summary>
        /// Test the property 'SystemCapacityBytes'
        /// </summary>
        [Test]
        public void SystemCapacityBytesTest()
        {
            // TODO unit test for the property 'SystemCapacityBytes'
        }
        /// <summary>
        /// Test the property 'SystemUsageBytes'
        /// </summary>
        [Test]
        public void SystemUsageBytesTest()
        {
            // TODO unit test for the property 'SystemUsageBytes'
        }
        /// <summary>
        /// Test the property 'TotalPhysicalRawUsageBytes'
        /// </summary>
        [Test]
        public void TotalPhysicalRawUsageBytesTest()
        {
            // TODO unit test for the property 'TotalPhysicalRawUsageBytes'
        }
        /// <summary>
        /// Test the property 'TotalPhysicalUsageBytes'
        /// </summary>
        [Test]
        public void TotalPhysicalUsageBytesTest()
        {
            // TODO unit test for the property 'TotalPhysicalUsageBytes'
        }
        /// <summary>
        /// Test the property 'WriteIos'
        /// </summary>
        [Test]
        public void WriteIosTest()
        {
            // TODO unit test for the property 'WriteIos'
        }
        /// <summary>
        /// Test the property 'WriteLatencyMsecs'
        /// </summary>
        [Test]
        public void WriteLatencyMsecsTest()
        {
            // TODO unit test for the property 'WriteLatencyMsecs'
        }

    }

}
