/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LogicalStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LogicalStatsTests
    {
        // TODO uncomment below to declare an instance variable for LogicalStats
        //private LogicalStats instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LogicalStats
            //instance = new LogicalStats();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LogicalStats
        /// </summary>
        [Test]
        public void LogicalStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LogicalStats
            //Assert.IsInstanceOfType<LogicalStats> (instance, "variable 'instance' is a LogicalStats");
        }


        /// <summary>
        /// Test the property 'TotalLogicalUsageBytes'
        /// </summary>
        [Test]
        public void TotalLogicalUsageBytesTest()
        {
            // TODO unit test for the property 'TotalLogicalUsageBytes'
        }

    }

}
