/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NetappClusterInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NetappClusterInfoTests
    {
        // TODO uncomment below to declare an instance variable for NetappClusterInfo
        //private NetappClusterInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NetappClusterInfo
            //instance = new NetappClusterInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetappClusterInfo
        /// </summary>
        [Test]
        public void NetappClusterInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NetappClusterInfo
            //Assert.IsInstanceOfType<NetappClusterInfo> (instance, "variable 'instance' is a NetappClusterInfo");
        }


        /// <summary>
        /// Test the property 'ContactInfo'
        /// </summary>
        [Test]
        public void ContactInfoTest()
        {
            // TODO unit test for the property 'ContactInfo'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }

    }

}
