/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OutputSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OutputSpecTests
    {
        // TODO uncomment below to declare an instance variable for OutputSpec
        //private OutputSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OutputSpec
            //instance = new OutputSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OutputSpec
        /// </summary>
        [Test]
        public void OutputSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OutputSpec
            //Assert.IsInstanceOfType<OutputSpec> (instance, "variable 'instance' is a OutputSpec");
        }


        /// <summary>
        /// Test the property 'NumReduceShards'
        /// </summary>
        [Test]
        public void NumReduceShardsTest()
        {
            // TODO unit test for the property 'NumReduceShards'
        }
        /// <summary>
        /// Test the property 'OutputDir'
        /// </summary>
        [Test]
        public void OutputDirTest()
        {
            // TODO unit test for the property 'OutputDir'
        }
        /// <summary>
        /// Test the property 'PartitionId'
        /// </summary>
        [Test]
        public void PartitionIdTest()
        {
            // TODO unit test for the property 'PartitionId'
        }
        /// <summary>
        /// Test the property 'ReduceOutputPrefix'
        /// </summary>
        [Test]
        public void ReduceOutputPrefixTest()
        {
            // TODO unit test for the property 'ReduceOutputPrefix'
        }
        /// <summary>
        /// Test the property 'ViewBoxId'
        /// </summary>
        [Test]
        public void ViewBoxIdTest()
        {
            // TODO unit test for the property 'ViewBoxId'
        }
        /// <summary>
        /// Test the property 'ViewName'
        /// </summary>
        [Test]
        public void ViewNameTest()
        {
            // TODO unit test for the property 'ViewName'
        }

    }

}
