/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtectionJobRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtectionJobRequestBodyTests
    {
        // TODO uncomment below to declare an instance variable for ProtectionJobRequestBody
        //private ProtectionJobRequestBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtectionJobRequestBody
            //instance = new ProtectionJobRequestBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtectionJobRequestBody
        /// </summary>
        [Test]
        public void ProtectionJobRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtectionJobRequestBody
            //Assert.IsInstanceOfType<ProtectionJobRequestBody> (instance, "variable 'instance' is a ProtectionJobRequestBody");
        }


        /// <summary>
        /// Test the property 'AbortInBlackoutPeriod'
        /// </summary>
        [Test]
        public void AbortInBlackoutPeriodTest()
        {
            // TODO unit test for the property 'AbortInBlackoutPeriod'
        }
        /// <summary>
        /// Test the property 'AlertingPolicy'
        /// </summary>
        [Test]
        public void AlertingPolicyTest()
        {
            // TODO unit test for the property 'AlertingPolicy'
        }
        /// <summary>
        /// Test the property 'CloudParameters'
        /// </summary>
        [Test]
        public void CloudParametersTest()
        {
            // TODO unit test for the property 'CloudParameters'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EndTimeUsecs'
        /// </summary>
        [Test]
        public void EndTimeUsecsTest()
        {
            // TODO unit test for the property 'EndTimeUsecs'
        }
        /// <summary>
        /// Test the property 'Environment'
        /// </summary>
        [Test]
        public void EnvironmentTest()
        {
            // TODO unit test for the property 'Environment'
        }
        /// <summary>
        /// Test the property 'EnvironmentParameters'
        /// </summary>
        [Test]
        public void EnvironmentParametersTest()
        {
            // TODO unit test for the property 'EnvironmentParameters'
        }
        /// <summary>
        /// Test the property 'ExcludeSourceIds'
        /// </summary>
        [Test]
        public void ExcludeSourceIdsTest()
        {
            // TODO unit test for the property 'ExcludeSourceIds'
        }
        /// <summary>
        /// Test the property 'ExcludeVmTagIds'
        /// </summary>
        [Test]
        public void ExcludeVmTagIdsTest()
        {
            // TODO unit test for the property 'ExcludeVmTagIds'
        }
        /// <summary>
        /// Test the property 'FullProtectionSlaTimeMins'
        /// </summary>
        [Test]
        public void FullProtectionSlaTimeMinsTest()
        {
            // TODO unit test for the property 'FullProtectionSlaTimeMins'
        }
        /// <summary>
        /// Test the property 'FullProtectionStartTime'
        /// </summary>
        [Test]
        public void FullProtectionStartTimeTest()
        {
            // TODO unit test for the property 'FullProtectionStartTime'
        }
        /// <summary>
        /// Test the property 'IncrementalProtectionSlaTimeMins'
        /// </summary>
        [Test]
        public void IncrementalProtectionSlaTimeMinsTest()
        {
            // TODO unit test for the property 'IncrementalProtectionSlaTimeMins'
        }
        /// <summary>
        /// Test the property 'IncrementalProtectionStartTime'
        /// </summary>
        [Test]
        public void IncrementalProtectionStartTimeTest()
        {
            // TODO unit test for the property 'IncrementalProtectionStartTime'
        }
        /// <summary>
        /// Test the property 'IndexingPolicy'
        /// </summary>
        [Test]
        public void IndexingPolicyTest()
        {
            // TODO unit test for the property 'IndexingPolicy'
        }
        /// <summary>
        /// Test the property 'LeverageStorageSnapshots'
        /// </summary>
        [Test]
        public void LeverageStorageSnapshotsTest()
        {
            // TODO unit test for the property 'LeverageStorageSnapshots'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParentSourceId'
        /// </summary>
        [Test]
        public void ParentSourceIdTest()
        {
            // TODO unit test for the property 'ParentSourceId'
        }
        /// <summary>
        /// Test the property 'PolicyId'
        /// </summary>
        [Test]
        public void PolicyIdTest()
        {
            // TODO unit test for the property 'PolicyId'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'QosType'
        /// </summary>
        [Test]
        public void QosTypeTest()
        {
            // TODO unit test for the property 'QosType'
        }
        /// <summary>
        /// Test the property 'Quiesce'
        /// </summary>
        [Test]
        public void QuiesceTest()
        {
            // TODO unit test for the property 'Quiesce'
        }
        /// <summary>
        /// Test the property 'RemoteScript'
        /// </summary>
        [Test]
        public void RemoteScriptTest()
        {
            // TODO unit test for the property 'RemoteScript'
        }
        /// <summary>
        /// Test the property 'SourceIds'
        /// </summary>
        [Test]
        public void SourceIdsTest()
        {
            // TODO unit test for the property 'SourceIds'
        }
        /// <summary>
        /// Test the property 'SourceSpecialParameters'
        /// </summary>
        [Test]
        public void SourceSpecialParametersTest()
        {
            // TODO unit test for the property 'SourceSpecialParameters'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
        /// <summary>
        /// Test the property 'ViewBoxId'
        /// </summary>
        [Test]
        public void ViewBoxIdTest()
        {
            // TODO unit test for the property 'ViewBoxId'
        }
        /// <summary>
        /// Test the property 'ViewName'
        /// </summary>
        [Test]
        public void ViewNameTest()
        {
            // TODO unit test for the property 'ViewName'
        }
        /// <summary>
        /// Test the property 'VmTagIds'
        /// </summary>
        [Test]
        public void VmTagIdsTest()
        {
            // TODO unit test for the property 'VmTagIds'
        }

    }

}
