/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtectedVmInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtectedVmInfoTests
    {
        // TODO uncomment below to declare an instance variable for ProtectedVmInfo
        //private ProtectedVmInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtectedVmInfo
            //instance = new ProtectedVmInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtectedVmInfo
        /// </summary>
        [Test]
        public void ProtectedVmInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtectedVmInfo
            //Assert.IsInstanceOfType<ProtectedVmInfo> (instance, "variable 'instance' is a ProtectedVmInfo");
        }


        /// <summary>
        /// Test the property 'ProtectionJobs'
        /// </summary>
        [Test]
        public void ProtectionJobsTest()
        {
            // TODO unit test for the property 'ProtectionJobs'
        }
        /// <summary>
        /// Test the property 'ProtectionPolicies'
        /// </summary>
        [Test]
        public void ProtectionPoliciesTest()
        {
            // TODO unit test for the property 'ProtectionPolicies'
        }
        /// <summary>
        /// Test the property 'ProtectionSource'
        /// </summary>
        [Test]
        public void ProtectionSourceTest()
        {
            // TODO unit test for the property 'ProtectionSource'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }

    }

}
