/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtectionSourceSnapshotInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtectionSourceSnapshotInformationTests
    {
        // TODO uncomment below to declare an instance variable for ProtectionSourceSnapshotInformation
        //private ProtectionSourceSnapshotInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtectionSourceSnapshotInformation
            //instance = new ProtectionSourceSnapshotInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtectionSourceSnapshotInformation
        /// </summary>
        [Test]
        public void ProtectionSourceSnapshotInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtectionSourceSnapshotInformation
            //Assert.IsInstanceOfType<ProtectionSourceSnapshotInformation> (instance, "variable 'instance' is a ProtectionSourceSnapshotInformation");
        }


        /// <summary>
        /// Test the property 'CopyTasks'
        /// </summary>
        [Test]
        public void CopyTasksTest()
        {
            // TODO unit test for the property 'CopyTasks'
        }
        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Test]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'JobName'
        /// </summary>
        [Test]
        public void JobNameTest()
        {
            // TODO unit test for the property 'JobName'
        }
        /// <summary>
        /// Test the property 'JobRunId'
        /// </summary>
        [Test]
        public void JobRunIdTest()
        {
            // TODO unit test for the property 'JobRunId'
        }
        /// <summary>
        /// Test the property 'LastRunEndTimeUsecs'
        /// </summary>
        [Test]
        public void LastRunEndTimeUsecsTest()
        {
            // TODO unit test for the property 'LastRunEndTimeUsecs'
        }
        /// <summary>
        /// Test the property 'LastRunStartTimeUsecs'
        /// </summary>
        [Test]
        public void LastRunStartTimeUsecsTest()
        {
            // TODO unit test for the property 'LastRunStartTimeUsecs'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'NumBytesRead'
        /// </summary>
        [Test]
        public void NumBytesReadTest()
        {
            // TODO unit test for the property 'NumBytesRead'
        }
        /// <summary>
        /// Test the property 'NumLogicalBytesProtected'
        /// </summary>
        [Test]
        public void NumLogicalBytesProtectedTest()
        {
            // TODO unit test for the property 'NumLogicalBytesProtected'
        }
        /// <summary>
        /// Test the property 'PaginationCookie'
        /// </summary>
        [Test]
        public void PaginationCookieTest()
        {
            // TODO unit test for the property 'PaginationCookie'
        }
        /// <summary>
        /// Test the property 'RunStatus'
        /// </summary>
        [Test]
        public void RunStatusTest()
        {
            // TODO unit test for the property 'RunStatus'
        }
        /// <summary>
        /// Test the property 'RunType'
        /// </summary>
        [Test]
        public void RunTypeTest()
        {
            // TODO unit test for the property 'RunType'
        }

    }

}
