/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtectionJobUid1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtectionJobUid1Tests
    {
        // TODO uncomment below to declare an instance variable for ProtectionJobUid1
        //private ProtectionJobUid1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtectionJobUid1
            //instance = new ProtectionJobUid1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtectionJobUid1
        /// </summary>
        [Test]
        public void ProtectionJobUid1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtectionJobUid1
            //Assert.IsInstanceOfType<ProtectionJobUid1> (instance, "variable 'instance' is a ProtectionJobUid1");
        }


        /// <summary>
        /// Test the property 'ClusterId'
        /// </summary>
        [Test]
        public void ClusterIdTest()
        {
            // TODO unit test for the property 'ClusterId'
        }
        /// <summary>
        /// Test the property 'ClusterIncarnationId'
        /// </summary>
        [Test]
        public void ClusterIncarnationIdTest()
        {
            // TODO unit test for the property 'ClusterIncarnationId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
