/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_Tests
    {
        // TODO uncomment below to declare an instance variable for ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_
        //private ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_
            //instance = new ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_
        /// </summary>
        [Test]
        public void ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_
            //Assert.IsInstanceOfType<ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_> (instance, "variable 'instance' is a ProtectionSummaryInformationOfARegisteredProtectionSourceTreeOrtheCohesityCluster_");
        }


        /// <summary>
        /// Test the property 'ProtectedCount'
        /// </summary>
        [Test]
        public void ProtectedCountTest()
        {
            // TODO unit test for the property 'ProtectedCount'
        }
        /// <summary>
        /// Test the property 'ProtectedSize'
        /// </summary>
        [Test]
        public void ProtectedSizeTest()
        {
            // TODO unit test for the property 'ProtectedSize'
        }
        /// <summary>
        /// Test the property 'UnprotectedCount'
        /// </summary>
        [Test]
        public void UnprotectedCountTest()
        {
            // TODO unit test for the property 'UnprotectedCount'
        }
        /// <summary>
        /// Test the property 'UnprotectedSize'
        /// </summary>
        [Test]
        public void UnprotectedSizeTest()
        {
            // TODO unit test for the property 'UnprotectedSize'
        }

    }

}
