/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QStarServerCredentials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QStarServerCredentialsTests
    {
        // TODO uncomment below to declare an instance variable for QStarServerCredentials
        //private QStarServerCredentials instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QStarServerCredentials
            //instance = new QStarServerCredentials();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QStarServerCredentials
        /// </summary>
        [Test]
        public void QStarServerCredentialsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QStarServerCredentials
            //Assert.IsInstanceOfType<QStarServerCredentials> (instance, "variable 'instance' is a QStarServerCredentials");
        }


        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'IntegralVolumeNames'
        /// </summary>
        [Test]
        public void IntegralVolumeNamesTest()
        {
            // TODO unit test for the property 'IntegralVolumeNames'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'ShareType'
        /// </summary>
        [Test]
        public void ShareTypeTest()
        {
            // TODO unit test for the property 'ShareType'
        }
        /// <summary>
        /// Test the property 'UseHttps'
        /// </summary>
        [Test]
        public void UseHttpsTest()
        {
            // TODO unit test for the property 'UseHttps'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
