/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuotaPolicy3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuotaPolicy3Tests
    {
        // TODO uncomment below to declare an instance variable for QuotaPolicy3
        //private QuotaPolicy3 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuotaPolicy3
            //instance = new QuotaPolicy3();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuotaPolicy3
        /// </summary>
        [Test]
        public void QuotaPolicy3InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuotaPolicy3
            //Assert.IsInstanceOfType<QuotaPolicy3> (instance, "variable 'instance' is a QuotaPolicy3");
        }


        /// <summary>
        /// Test the property 'AlertLimit'
        /// </summary>
        [Test]
        public void AlertLimitTest()
        {
            // TODO unit test for the property 'AlertLimit'
        }
        /// <summary>
        /// Test the property 'HardLimit'
        /// </summary>
        [Test]
        public void HardLimitTest()
        {
            // TODO unit test for the property 'HardLimit'
        }
        /// <summary>
        /// Test the property 'AlertLimitBytes'
        /// </summary>
        [Test]
        public void AlertLimitBytesTest()
        {
            // TODO unit test for the property 'AlertLimitBytes'
        }
        /// <summary>
        /// Test the property 'AlertThresholdPercentage'
        /// </summary>
        [Test]
        public void AlertThresholdPercentageTest()
        {
            // TODO unit test for the property 'AlertThresholdPercentage'
        }
        /// <summary>
        /// Test the property 'HardLimitBytes'
        /// </summary>
        [Test]
        public void HardLimitBytesTest()
        {
            // TODO unit test for the property 'HardLimitBytes'
        }

    }

}
