/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RegisteredSourceInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegisteredSourceInfoTests
    {
        // TODO uncomment below to declare an instance variable for RegisteredSourceInfo
        //private RegisteredSourceInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegisteredSourceInfo
            //instance = new RegisteredSourceInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegisteredSourceInfo
        /// </summary>
        [Test]
        public void RegisteredSourceInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RegisteredSourceInfo
            //Assert.IsInstanceOfType<RegisteredSourceInfo> (instance, "variable 'instance' is a RegisteredSourceInfo");
        }


        /// <summary>
        /// Test the property 'AccessInfo'
        /// </summary>
        [Test]
        public void AccessInfoTest()
        {
            // TODO unit test for the property 'AccessInfo'
        }
        /// <summary>
        /// Test the property 'AuthenticationErrorMessage'
        /// </summary>
        [Test]
        public void AuthenticationErrorMessageTest()
        {
            // TODO unit test for the property 'AuthenticationErrorMessage'
        }
        /// <summary>
        /// Test the property 'AuthenticationStatus'
        /// </summary>
        [Test]
        public void AuthenticationStatusTest()
        {
            // TODO unit test for the property 'AuthenticationStatus'
        }
        /// <summary>
        /// Test the property 'Environments'
        /// </summary>
        [Test]
        public void EnvironmentsTest()
        {
            // TODO unit test for the property 'Environments'
        }
        /// <summary>
        /// Test the property 'MinimumFreeSpaceGB'
        /// </summary>
        [Test]
        public void MinimumFreeSpaceGBTest()
        {
            // TODO unit test for the property 'MinimumFreeSpaceGB'
        }
        /// <summary>
        /// Test the property 'NasMountCredentials'
        /// </summary>
        [Test]
        public void NasMountCredentialsTest()
        {
            // TODO unit test for the property 'NasMountCredentials'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'RefreshErrorMessage'
        /// </summary>
        [Test]
        public void RefreshErrorMessageTest()
        {
            // TODO unit test for the property 'RefreshErrorMessage'
        }
        /// <summary>
        /// Test the property 'RefreshTimeUsecs'
        /// </summary>
        [Test]
        public void RefreshTimeUsecsTest()
        {
            // TODO unit test for the property 'RefreshTimeUsecs'
        }
        /// <summary>
        /// Test the property 'RegistrationTimeUsecs'
        /// </summary>
        [Test]
        public void RegistrationTimeUsecsTest()
        {
            // TODO unit test for the property 'RegistrationTimeUsecs'
        }
        /// <summary>
        /// Test the property 'ThrottlingPolicy'
        /// </summary>
        [Test]
        public void ThrottlingPolicyTest()
        {
            // TODO unit test for the property 'ThrottlingPolicy'
        }
        /// <summary>
        /// Test the property 'ThrottlingPolicyOverrides'
        /// </summary>
        [Test]
        public void ThrottlingPolicyOverridesTest()
        {
            // TODO unit test for the property 'ThrottlingPolicyOverrides'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'WarningMessages'
        /// </summary>
        [Test]
        public void WarningMessagesTest()
        {
            // TODO unit test for the property 'WarningMessages'
        }

    }

}
