/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RegisterRemoteCluster
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegisterRemoteClusterTests
    {
        // TODO uncomment below to declare an instance variable for RegisterRemoteCluster
        //private RegisterRemoteCluster instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegisterRemoteCluster
            //instance = new RegisterRemoteCluster();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegisterRemoteCluster
        /// </summary>
        [Test]
        public void RegisterRemoteClusterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RegisterRemoteCluster
            //Assert.IsInstanceOfType<RegisterRemoteCluster> (instance, "variable 'instance' is a RegisterRemoteCluster");
        }


        /// <summary>
        /// Test the property 'AllEndpointsReachable'
        /// </summary>
        [Test]
        public void AllEndpointsReachableTest()
        {
            // TODO unit test for the property 'AllEndpointsReachable'
        }
        /// <summary>
        /// Test the property 'BandwidthLimit'
        /// </summary>
        [Test]
        public void BandwidthLimitTest()
        {
            // TODO unit test for the property 'BandwidthLimit'
        }
        /// <summary>
        /// Test the property 'ClearInterfaces'
        /// </summary>
        [Test]
        public void ClearInterfacesTest()
        {
            // TODO unit test for the property 'ClearInterfaces'
        }
        /// <summary>
        /// Test the property 'ClearVlanId'
        /// </summary>
        [Test]
        public void ClearVlanIdTest()
        {
            // TODO unit test for the property 'ClearVlanId'
        }
        /// <summary>
        /// Test the property 'ClusterId'
        /// </summary>
        [Test]
        public void ClusterIdTest()
        {
            // TODO unit test for the property 'ClusterId'
        }
        /// <summary>
        /// Test the property 'CompressionEnabled'
        /// </summary>
        [Test]
        public void CompressionEnabledTest()
        {
            // TODO unit test for the property 'CompressionEnabled'
        }
        /// <summary>
        /// Test the property 'EncryptionKey'
        /// </summary>
        [Test]
        public void EncryptionKeyTest()
        {
            // TODO unit test for the property 'EncryptionKey'
        }
        /// <summary>
        /// Test the property 'NetworkInterfaceGroup'
        /// </summary>
        [Test]
        public void NetworkInterfaceGroupTest()
        {
            // TODO unit test for the property 'NetworkInterfaceGroup'
        }
        /// <summary>
        /// Test the property 'NetworkInterfaceIds'
        /// </summary>
        [Test]
        public void NetworkInterfaceIdsTest()
        {
            // TODO unit test for the property 'NetworkInterfaceIds'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'PurposeRemoteAccess'
        /// </summary>
        [Test]
        public void PurposeRemoteAccessTest()
        {
            // TODO unit test for the property 'PurposeRemoteAccess'
        }
        /// <summary>
        /// Test the property 'PurposeReplication'
        /// </summary>
        [Test]
        public void PurposeReplicationTest()
        {
            // TODO unit test for the property 'PurposeReplication'
        }
        /// <summary>
        /// Test the property 'RemoteAccessCredentials'
        /// </summary>
        [Test]
        public void RemoteAccessCredentialsTest()
        {
            // TODO unit test for the property 'RemoteAccessCredentials'
        }
        /// <summary>
        /// Test the property 'RemoteIps'
        /// </summary>
        [Test]
        public void RemoteIpsTest()
        {
            // TODO unit test for the property 'RemoteIps'
        }
        /// <summary>
        /// Test the property 'RemoteIrisPorts'
        /// </summary>
        [Test]
        public void RemoteIrisPortsTest()
        {
            // TODO unit test for the property 'RemoteIrisPorts'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'ValidateOnly'
        /// </summary>
        [Test]
        public void ValidateOnlyTest()
        {
            // TODO unit test for the property 'ValidateOnly'
        }
        /// <summary>
        /// Test the property 'ViewBoxPairInfo'
        /// </summary>
        [Test]
        public void ViewBoxPairInfoTest()
        {
            // TODO unit test for the property 'ViewBoxPairInfo'
        }
        /// <summary>
        /// Test the property 'VlanId'
        /// </summary>
        [Test]
        public void VlanIdTest()
        {
            // TODO unit test for the property 'VlanId'
        }

    }

}
