/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReplicationTarget_
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplicationTarget_Tests
    {
        // TODO uncomment below to declare an instance variable for ReplicationTarget_
        //private ReplicationTarget_ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplicationTarget_
            //instance = new ReplicationTarget_();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplicationTarget_
        /// </summary>
        [Test]
        public void ReplicationTarget_InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplicationTarget_
            //Assert.IsInstanceOfType<ReplicationTarget_> (instance, "variable 'instance' is a ReplicationTarget_");
        }


        /// <summary>
        /// Test the property 'ClusterId'
        /// </summary>
        [Test]
        public void ClusterIdTest()
        {
            // TODO unit test for the property 'ClusterId'
        }
        /// <summary>
        /// Test the property 'ClusterName'
        /// </summary>
        [Test]
        public void ClusterNameTest()
        {
            // TODO unit test for the property 'ClusterName'
        }

    }

}
