/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RestoreObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestoreObjectTests
    {
        // TODO uncomment below to declare an instance variable for RestoreObject
        //private RestoreObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestoreObject
            //instance = new RestoreObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestoreObject
        /// </summary>
        [Test]
        public void RestoreObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestoreObject
            //Assert.IsInstanceOfType<RestoreObject> (instance, "variable 'instance' is a RestoreObject");
        }


        /// <summary>
        /// Test the property 'ArchivalTarget'
        /// </summary>
        [Test]
        public void ArchivalTargetTest()
        {
            // TODO unit test for the property 'ArchivalTarget'
        }
        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Test]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'JobRunId'
        /// </summary>
        [Test]
        public void JobRunIdTest()
        {
            // TODO unit test for the property 'JobRunId'
        }
        /// <summary>
        /// Test the property 'JobUid'
        /// </summary>
        [Test]
        public void JobUidTest()
        {
            // TODO unit test for the property 'JobUid'
        }
        /// <summary>
        /// Test the property 'ProtectionSourceId'
        /// </summary>
        [Test]
        public void ProtectionSourceIdTest()
        {
            // TODO unit test for the property 'ProtectionSourceId'
        }
        /// <summary>
        /// Test the property 'StartedTimeUsecs'
        /// </summary>
        [Test]
        public void StartedTimeUsecsTest()
        {
            // TODO unit test for the property 'StartedTimeUsecs'
        }

    }

}
