/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RestoreObjectState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestoreObjectStateTests
    {
        // TODO uncomment below to declare an instance variable for RestoreObjectState
        //private RestoreObjectState instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestoreObjectState
            //instance = new RestoreObjectState();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestoreObjectState
        /// </summary>
        [Test]
        public void RestoreObjectStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestoreObjectState
            //Assert.IsInstanceOfType<RestoreObjectState> (instance, "variable 'instance' is a RestoreObjectState");
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'ObjectStatus'
        /// </summary>
        [Test]
        public void ObjectStatusTest()
        {
            // TODO unit test for the property 'ObjectStatus'
        }
        /// <summary>
        /// Test the property 'ResourcePoolId'
        /// </summary>
        [Test]
        public void ResourcePoolIdTest()
        {
            // TODO unit test for the property 'ResourcePoolId'
        }
        /// <summary>
        /// Test the property 'RestoredObjectId'
        /// </summary>
        [Test]
        public void RestoredObjectIdTest()
        {
            // TODO unit test for the property 'RestoredObjectId'
        }
        /// <summary>
        /// Test the property 'SourceObjectId'
        /// </summary>
        [Test]
        public void SourceObjectIdTest()
        {
            // TODO unit test for the property 'SourceObjectId'
        }

    }

}
