/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Role
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RoleTests
    {
        // TODO uncomment below to declare an instance variable for Role
        //private Role instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Role
            //instance = new Role();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Role
        /// </summary>
        [Test]
        public void RoleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Role
            //Assert.IsInstanceOfType<Role> (instance, "variable 'instance' is a Role");
        }


        /// <summary>
        /// Test the property 'CreatedTimeMsecs'
        /// </summary>
        [Test]
        public void CreatedTimeMsecsTest()
        {
            // TODO unit test for the property 'CreatedTimeMsecs'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IsCustomRole'
        /// </summary>
        [Test]
        public void IsCustomRoleTest()
        {
            // TODO unit test for the property 'IsCustomRole'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'LastUpdatedTimeMsecs'
        /// </summary>
        [Test]
        public void LastUpdatedTimeMsecsTest()
        {
            // TODO unit test for the property 'LastUpdatedTimeMsecs'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Privileges'
        /// </summary>
        [Test]
        public void PrivilegesTest()
        {
            // TODO unit test for the property 'Privileges'
        }

    }

}
