/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SmbActiveSession
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SmbActiveSessionTests
    {
        // TODO uncomment below to declare an instance variable for SmbActiveSession
        //private SmbActiveSession instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SmbActiveSession
            //instance = new SmbActiveSession();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmbActiveSession
        /// </summary>
        [Test]
        public void SmbActiveSessionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SmbActiveSession
            //Assert.IsInstanceOfType<SmbActiveSession> (instance, "variable 'instance' is a SmbActiveSession");
        }


        /// <summary>
        /// Test the property 'ActiveOpens'
        /// </summary>
        [Test]
        public void ActiveOpensTest()
        {
            // TODO unit test for the property 'ActiveOpens'
        }
        /// <summary>
        /// Test the property 'ClientIp'
        /// </summary>
        [Test]
        public void ClientIpTest()
        {
            // TODO unit test for the property 'ClientIp'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'ServerIp'
        /// </summary>
        [Test]
        public void ServerIpTest()
        {
            // TODO unit test for the property 'ServerIp'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Test]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
