/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SnapshotTarget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SnapshotTargetTests
    {
        // TODO uncomment below to declare an instance variable for SnapshotTarget
        //private SnapshotTarget instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SnapshotTarget
            //instance = new SnapshotTarget();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SnapshotTarget
        /// </summary>
        [Test]
        public void SnapshotTargetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SnapshotTarget
            //Assert.IsInstanceOfType<SnapshotTarget> (instance, "variable 'instance' is a SnapshotTarget");
        }


        /// <summary>
        /// Test the property 'ArchivalTarget'
        /// </summary>
        [Test]
        public void ArchivalTargetTest()
        {
            // TODO unit test for the property 'ArchivalTarget'
        }
        /// <summary>
        /// Test the property 'ReplicationTarget'
        /// </summary>
        [Test]
        public void ReplicationTargetTest()
        {
            // TODO unit test for the property 'ReplicationTarget'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
