/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SnapshotCopyTask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SnapshotCopyTaskTests
    {
        // TODO uncomment below to declare an instance variable for SnapshotCopyTask
        //private SnapshotCopyTask instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SnapshotCopyTask
            //instance = new SnapshotCopyTask();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SnapshotCopyTask
        /// </summary>
        [Test]
        public void SnapshotCopyTaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SnapshotCopyTask
            //Assert.IsInstanceOfType<SnapshotCopyTask> (instance, "variable 'instance' is a SnapshotCopyTask");
        }


        /// <summary>
        /// Test the property 'CopyStatus'
        /// </summary>
        [Test]
        public void CopyStatusTest()
        {
            // TODO unit test for the property 'CopyStatus'
        }
        /// <summary>
        /// Test the property 'ExpiryTimeUsecs'
        /// </summary>
        [Test]
        public void ExpiryTimeUsecsTest()
        {
            // TODO unit test for the property 'ExpiryTimeUsecs'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'SnapshotTarget'
        /// </summary>
        [Test]
        public void SnapshotTargetTest()
        {
            // TODO unit test for the property 'SnapshotTarget'
        }

    }

}
