/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SnapshotReplicationCopyPolicy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SnapshotReplicationCopyPolicyTests
    {
        // TODO uncomment below to declare an instance variable for SnapshotReplicationCopyPolicy
        //private SnapshotReplicationCopyPolicy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SnapshotReplicationCopyPolicy
            //instance = new SnapshotReplicationCopyPolicy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SnapshotReplicationCopyPolicy
        /// </summary>
        [Test]
        public void SnapshotReplicationCopyPolicyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SnapshotReplicationCopyPolicy
            //Assert.IsInstanceOfType<SnapshotReplicationCopyPolicy> (instance, "variable 'instance' is a SnapshotReplicationCopyPolicy");
        }


        /// <summary>
        /// Test the property 'CopyPartial'
        /// </summary>
        [Test]
        public void CopyPartialTest()
        {
            // TODO unit test for the property 'CopyPartial'
        }
        /// <summary>
        /// Test the property 'DaysToKeep'
        /// </summary>
        [Test]
        public void DaysToKeepTest()
        {
            // TODO unit test for the property 'DaysToKeep'
        }
        /// <summary>
        /// Test the property 'Multiplier'
        /// </summary>
        [Test]
        public void MultiplierTest()
        {
            // TODO unit test for the property 'Multiplier'
        }
        /// <summary>
        /// Test the property 'Periodicity'
        /// </summary>
        [Test]
        public void PeriodicityTest()
        {
            // TODO unit test for the property 'Periodicity'
        }
        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Test]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

    }

}
