/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SourcesForSid
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SourcesForSidTests
    {
        // TODO uncomment below to declare an instance variable for SourcesForSid
        //private SourcesForSid instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SourcesForSid
            //instance = new SourcesForSid();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SourcesForSid
        /// </summary>
        [Test]
        public void SourcesForSidInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SourcesForSid
            //Assert.IsInstanceOfType<SourcesForSid> (instance, "variable 'instance' is a SourcesForSid");
        }


        /// <summary>
        /// Test the property 'ProtectionSources'
        /// </summary>
        [Test]
        public void ProtectionSourcesTest()
        {
            // TODO unit test for the property 'ProtectionSources'
        }
        /// <summary>
        /// Test the property 'Sid'
        /// </summary>
        [Test]
        public void SidTest()
        {
            // TODO unit test for the property 'Sid'
        }
        /// <summary>
        /// Test the property 'Views'
        /// </summary>
        [Test]
        public void ViewsTest()
        {
            // TODO unit test for the property 'Views'
        }

    }

}
