/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SourceBackupStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SourceBackupStatusTests
    {
        // TODO uncomment below to declare an instance variable for SourceBackupStatus
        //private SourceBackupStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SourceBackupStatus
            //instance = new SourceBackupStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SourceBackupStatus
        /// </summary>
        [Test]
        public void SourceBackupStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SourceBackupStatus
            //Assert.IsInstanceOfType<SourceBackupStatus> (instance, "variable 'instance' is a SourceBackupStatus");
        }


        /// <summary>
        /// Test the property 'CurrentSnapshotInfo'
        /// </summary>
        [Test]
        public void CurrentSnapshotInfoTest()
        {
            // TODO unit test for the property 'CurrentSnapshotInfo'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'IsFullBackup'
        /// </summary>
        [Test]
        public void IsFullBackupTest()
        {
            // TODO unit test for the property 'IsFullBackup'
        }
        /// <summary>
        /// Test the property 'NumRestarts'
        /// </summary>
        [Test]
        public void NumRestartsTest()
        {
            // TODO unit test for the property 'NumRestarts'
        }
        /// <summary>
        /// Test the property 'ParentSourceId'
        /// </summary>
        [Test]
        public void ParentSourceIdTest()
        {
            // TODO unit test for the property 'ParentSourceId'
        }
        /// <summary>
        /// Test the property 'Quiesced'
        /// </summary>
        [Test]
        public void QuiescedTest()
        {
            // TODO unit test for the property 'Quiesced'
        }
        /// <summary>
        /// Test the property 'SlaViolated'
        /// </summary>
        [Test]
        public void SlaViolatedTest()
        {
            // TODO unit test for the property 'SlaViolated'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Test]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }

    }

}
