/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SourceSpecialParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SourceSpecialParameterTests
    {
        // TODO uncomment below to declare an instance variable for SourceSpecialParameter
        //private SourceSpecialParameter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SourceSpecialParameter
            //instance = new SourceSpecialParameter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SourceSpecialParameter
        /// </summary>
        [Test]
        public void SourceSpecialParameterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SourceSpecialParameter
            //Assert.IsInstanceOfType<SourceSpecialParameter> (instance, "variable 'instance' is a SourceSpecialParameter");
        }


        /// <summary>
        /// Test the property 'PhysicalSpecialParameters'
        /// </summary>
        [Test]
        public void PhysicalSpecialParametersTest()
        {
            // TODO unit test for the property 'PhysicalSpecialParameters'
        }
        /// <summary>
        /// Test the property 'SkipIndexing'
        /// </summary>
        [Test]
        public void SkipIndexingTest()
        {
            // TODO unit test for the property 'SkipIndexing'
        }
        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Test]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }
        /// <summary>
        /// Test the property 'SqlSpecialParameters'
        /// </summary>
        [Test]
        public void SqlSpecialParametersTest()
        {
            // TODO unit test for the property 'SqlSpecialParameters'
        }
        /// <summary>
        /// Test the property 'TruncateExchangeLog'
        /// </summary>
        [Test]
        public void TruncateExchangeLogTest()
        {
            // TODO unit test for the property 'TruncateExchangeLog'
        }
        /// <summary>
        /// Test the property 'VmCredentials'
        /// </summary>
        [Test]
        public void VmCredentialsTest()
        {
            // TODO unit test for the property 'VmCredentials'
        }
        /// <summary>
        /// Test the property 'VmwareSpecialParameters'
        /// </summary>
        [Test]
        public void VmwareSpecialParametersTest()
        {
            // TODO unit test for the property 'VmwareSpecialParameters'
        }

    }

}
