/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SqlProtectionSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SqlProtectionSourceTests
    {
        // TODO uncomment below to declare an instance variable for SqlProtectionSource
        //private SqlProtectionSource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SqlProtectionSource
            //instance = new SqlProtectionSource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SqlProtectionSource
        /// </summary>
        [Test]
        public void SqlProtectionSourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SqlProtectionSource
            //Assert.IsInstanceOfType<SqlProtectionSource> (instance, "variable 'instance' is a SqlProtectionSource");
        }


        /// <summary>
        /// Test the property 'IsAvailableForVssBackup'
        /// </summary>
        [Test]
        public void IsAvailableForVssBackupTest()
        {
            // TODO unit test for the property 'IsAvailableForVssBackup'
        }
        /// <summary>
        /// Test the property 'CreatedTimestamp'
        /// </summary>
        [Test]
        public void CreatedTimestampTest()
        {
            // TODO unit test for the property 'CreatedTimestamp'
        }
        /// <summary>
        /// Test the property 'DatabaseName'
        /// </summary>
        [Test]
        public void DatabaseNameTest()
        {
            // TODO unit test for the property 'DatabaseName'
        }
        /// <summary>
        /// Test the property 'DbAagEntityId'
        /// </summary>
        [Test]
        public void DbAagEntityIdTest()
        {
            // TODO unit test for the property 'DbAagEntityId'
        }
        /// <summary>
        /// Test the property 'DbAagName'
        /// </summary>
        [Test]
        public void DbAagNameTest()
        {
            // TODO unit test for the property 'DbAagName'
        }
        /// <summary>
        /// Test the property 'DbFiles'
        /// </summary>
        [Test]
        public void DbFilesTest()
        {
            // TODO unit test for the property 'DbFiles'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Test]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
        /// <summary>
        /// Test the property 'RecoveryModel'
        /// </summary>
        [Test]
        public void RecoveryModelTest()
        {
            // TODO unit test for the property 'RecoveryModel'
        }
        /// <summary>
        /// Test the property 'SqlServerDbState'
        /// </summary>
        [Test]
        public void SqlServerDbStateTest()
        {
            // TODO unit test for the property 'SqlServerDbState'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
