/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SqlRestoreParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SqlRestoreParametersTests
    {
        // TODO uncomment below to declare an instance variable for SqlRestoreParameters
        //private SqlRestoreParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SqlRestoreParameters
            //instance = new SqlRestoreParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SqlRestoreParameters
        /// </summary>
        [Test]
        public void SqlRestoreParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SqlRestoreParameters
            //Assert.IsInstanceOfType<SqlRestoreParameters> (instance, "variable 'instance' is a SqlRestoreParameters");
        }


        /// <summary>
        /// Test the property 'CaptureTailLogs'
        /// </summary>
        [Test]
        public void CaptureTailLogsTest()
        {
            // TODO unit test for the property 'CaptureTailLogs'
        }
        /// <summary>
        /// Test the property 'KeepOffline'
        /// </summary>
        [Test]
        public void KeepOfflineTest()
        {
            // TODO unit test for the property 'KeepOffline'
        }
        /// <summary>
        /// Test the property 'NewDatabaseName'
        /// </summary>
        [Test]
        public void NewDatabaseNameTest()
        {
            // TODO unit test for the property 'NewDatabaseName'
        }
        /// <summary>
        /// Test the property 'NewInstanceName'
        /// </summary>
        [Test]
        public void NewInstanceNameTest()
        {
            // TODO unit test for the property 'NewInstanceName'
        }
        /// <summary>
        /// Test the property 'RestoreTimeSecs'
        /// </summary>
        [Test]
        public void RestoreTimeSecsTest()
        {
            // TODO unit test for the property 'RestoreTimeSecs'
        }
        /// <summary>
        /// Test the property 'TargetDataFilesDirectory'
        /// </summary>
        [Test]
        public void TargetDataFilesDirectoryTest()
        {
            // TODO unit test for the property 'TargetDataFilesDirectory'
        }
        /// <summary>
        /// Test the property 'TargetLogFilesDirectory'
        /// </summary>
        [Test]
        public void TargetLogFilesDirectoryTest()
        {
            // TODO unit test for the property 'TargetLogFilesDirectory'
        }
        /// <summary>
        /// Test the property 'TargetSecondaryDataFilesDirectoryList'
        /// </summary>
        [Test]
        public void TargetSecondaryDataFilesDirectoryListTest()
        {
            // TODO unit test for the property 'TargetSecondaryDataFilesDirectoryList'
        }

    }

}
