/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Subnet_
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Subnet_Tests
    {
        // TODO uncomment below to declare an instance variable for Subnet_
        //private Subnet_ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Subnet_
            //instance = new Subnet_();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Subnet_
        /// </summary>
        [Test]
        public void Subnet_InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Subnet_
            //Assert.IsInstanceOfType<Subnet_> (instance, "variable 'instance' is a Subnet_");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Test]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }
        /// <summary>
        /// Test the property 'NetmaskBits'
        /// </summary>
        [Test]
        public void NetmaskBitsTest()
        {
            // TODO unit test for the property 'NetmaskBits'
        }
        /// <summary>
        /// Test the property 'NetmaskIp4'
        /// </summary>
        [Test]
        public void NetmaskIp4Test()
        {
            // TODO unit test for the property 'NetmaskIp4'
        }

    }

}
