/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TableOfContents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TableOfContentsTests
    {
        // TODO uncomment below to declare an instance variable for TableOfContents
        //private TableOfContents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TableOfContents
            //instance = new TableOfContents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TableOfContents
        /// </summary>
        [Test]
        public void TableOfContentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TableOfContents
            //Assert.IsInstanceOfType<TableOfContents> (instance, "variable 'instance' is a TableOfContents");
        }


        /// <summary>
        /// Test the property 'ActiveDirectory'
        /// </summary>
        [Test]
        public void ActiveDirectoryTest()
        {
            // TODO unit test for the property 'ActiveDirectory'
        }
        /// <summary>
        /// Test the property 'Cluster'
        /// </summary>
        [Test]
        public void ClusterTest()
        {
            // TODO unit test for the property 'Cluster'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'Partition'
        /// </summary>
        [Test]
        public void PartitionTest()
        {
            // TODO unit test for the property 'Partition'
        }
        /// <summary>
        /// Test the property 'PrincipalSource'
        /// </summary>
        [Test]
        public void PrincipalSourceTest()
        {
            // TODO unit test for the property 'PrincipalSource'
        }
        /// <summary>
        /// Test the property 'ProtectionJob'
        /// </summary>
        [Test]
        public void ProtectionJobTest()
        {
            // TODO unit test for the property 'ProtectionJob'
        }
        /// <summary>
        /// Test the property 'ProtectionPolicy'
        /// </summary>
        [Test]
        public void ProtectionPolicyTest()
        {
            // TODO unit test for the property 'ProtectionPolicy'
        }
        /// <summary>
        /// Test the property 'ProtectionSource'
        /// </summary>
        [Test]
        public void ProtectionSourceTest()
        {
            // TODO unit test for the property 'ProtectionSource'
        }
        /// <summary>
        /// Test the property 'RemoteCluster'
        /// </summary>
        [Test]
        public void RemoteClusterTest()
        {
            // TODO unit test for the property 'RemoteCluster'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'Sql'
        /// </summary>
        [Test]
        public void SqlTest()
        {
            // TODO unit test for the property 'Sql'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Vault'
        /// </summary>
        [Test]
        public void VaultTest()
        {
            // TODO unit test for the property 'Vault'
        }
        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Test]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }
        /// <summary>
        /// Test the property 'ViewBox'
        /// </summary>
        [Test]
        public void ViewBoxTest()
        {
            // TODO unit test for the property 'ViewBox'
        }

    }

}
