/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserQuotaAndUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserQuotaAndUsageTests
    {
        // TODO uncomment below to declare an instance variable for UserQuotaAndUsage
        //private UserQuotaAndUsage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserQuotaAndUsage
            //instance = new UserQuotaAndUsage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserQuotaAndUsage
        /// </summary>
        [Test]
        public void UserQuotaAndUsageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserQuotaAndUsage
            //Assert.IsInstanceOfType<UserQuotaAndUsage> (instance, "variable 'instance' is a UserQuotaAndUsage");
        }


        /// <summary>
        /// Test the property 'QuotaPolicy'
        /// </summary>
        [Test]
        public void QuotaPolicyTest()
        {
            // TODO unit test for the property 'QuotaPolicy'
        }
        /// <summary>
        /// Test the property 'Sid'
        /// </summary>
        [Test]
        public void SidTest()
        {
            // TODO unit test for the property 'Sid'
        }
        /// <summary>
        /// Test the property 'UnixUid'
        /// </summary>
        [Test]
        public void UnixUidTest()
        {
            // TODO unit test for the property 'UnixUid'
        }
        /// <summary>
        /// Test the property 'UsageBytes'
        /// </summary>
        [Test]
        public void UsageBytesTest()
        {
            // TODO unit test for the property 'UsageBytes'
        }

    }

}
