/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Vault
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VaultTests
    {
        // TODO uncomment below to declare an instance variable for Vault
        //private Vault instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Vault
            //instance = new Vault();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Vault
        /// </summary>
        [Test]
        public void VaultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Vault
            //Assert.IsInstanceOfType<Vault> (instance, "variable 'instance' is a Vault");
        }


        /// <summary>
        /// Test the property 'CompressionPolicy'
        /// </summary>
        [Test]
        public void CompressionPolicyTest()
        {
            // TODO unit test for the property 'CompressionPolicy'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Test]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
        /// <summary>
        /// Test the property 'CustomerManagingEncryptionKeys'
        /// </summary>
        [Test]
        public void CustomerManagingEncryptionKeysTest()
        {
            // TODO unit test for the property 'CustomerManagingEncryptionKeys'
        }
        /// <summary>
        /// Test the property 'DedupEnabled'
        /// </summary>
        [Test]
        public void DedupEnabledTest()
        {
            // TODO unit test for the property 'DedupEnabled'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DesiredWalLocation'
        /// </summary>
        [Test]
        public void DesiredWalLocationTest()
        {
            // TODO unit test for the property 'DesiredWalLocation'
        }
        /// <summary>
        /// Test the property 'EncryptionKeyFileDownloaded'
        /// </summary>
        [Test]
        public void EncryptionKeyFileDownloadedTest()
        {
            // TODO unit test for the property 'EncryptionKeyFileDownloaded'
        }
        /// <summary>
        /// Test the property 'EncryptionPolicy'
        /// </summary>
        [Test]
        public void EncryptionPolicyTest()
        {
            // TODO unit test for the property 'EncryptionPolicy'
        }
        /// <summary>
        /// Test the property 'FullArchiveIntervalDays'
        /// </summary>
        [Test]
        public void FullArchiveIntervalDaysTest()
        {
            // TODO unit test for the property 'FullArchiveIntervalDays'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IncrementalArchivesEnabled'
        /// </summary>
        [Test]
        public void IncrementalArchivesEnabledTest()
        {
            // TODO unit test for the property 'IncrementalArchivesEnabled'
        }
        /// <summary>
        /// Test the property 'KeyFileDownloadTimeUsecs'
        /// </summary>
        [Test]
        public void KeyFileDownloadTimeUsecsTest()
        {
            // TODO unit test for the property 'KeyFileDownloadTimeUsecs'
        }
        /// <summary>
        /// Test the property 'KeyFileDownloadUser'
        /// </summary>
        [Test]
        public void KeyFileDownloadUserTest()
        {
            // TODO unit test for the property 'KeyFileDownloadUser'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'UsageType'
        /// </summary>
        [Test]
        public void UsageTypeTest()
        {
            // TODO unit test for the property 'UsageType'
        }

    }

}
