/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ViewBox
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ViewBoxTests
    {
        // TODO uncomment below to declare an instance variable for ViewBox
        //private ViewBox instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ViewBox
            //instance = new ViewBox();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ViewBox
        /// </summary>
        [Test]
        public void ViewBoxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ViewBox
            //Assert.IsInstanceOfType<ViewBox> (instance, "variable 'instance' is a ViewBox");
        }


        /// <summary>
        /// Test the property 'AdDomainName'
        /// </summary>
        [Test]
        public void AdDomainNameTest()
        {
            // TODO unit test for the property 'AdDomainName'
        }
        /// <summary>
        /// Test the property 'ClusterPartitionId'
        /// </summary>
        [Test]
        public void ClusterPartitionIdTest()
        {
            // TODO unit test for the property 'ClusterPartitionId'
        }
        /// <summary>
        /// Test the property 'ClusterPartitionName'
        /// </summary>
        [Test]
        public void ClusterPartitionNameTest()
        {
            // TODO unit test for the property 'ClusterPartitionName'
        }
        /// <summary>
        /// Test the property 'DefaultUserQuotaPolicy'
        /// </summary>
        [Test]
        public void DefaultUserQuotaPolicyTest()
        {
            // TODO unit test for the property 'DefaultUserQuotaPolicy'
        }
        /// <summary>
        /// Test the property 'DefaultViewQuotaPolicy'
        /// </summary>
        [Test]
        public void DefaultViewQuotaPolicyTest()
        {
            // TODO unit test for the property 'DefaultViewQuotaPolicy'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PhysicalQuota'
        /// </summary>
        [Test]
        public void PhysicalQuotaTest()
        {
            // TODO unit test for the property 'PhysicalQuota'
        }
        /// <summary>
        /// Test the property 'RemovalState'
        /// </summary>
        [Test]
        public void RemovalStateTest()
        {
            // TODO unit test for the property 'RemovalState'
        }
        /// <summary>
        /// Test the property 'S3BucketsAllowed'
        /// </summary>
        [Test]
        public void S3BucketsAllowedTest()
        {
            // TODO unit test for the property 'S3BucketsAllowed'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'StoragePolicy'
        /// </summary>
        [Test]
        public void StoragePolicyTest()
        {
            // TODO unit test for the property 'StoragePolicy'
        }
        /// <summary>
        /// Test the property 'TreatFileSyncAsDataSync'
        /// </summary>
        [Test]
        public void TreatFileSyncAsDataSyncTest()
        {
            // TODO unit test for the property 'TreatFileSyncAsDataSync'
        }

    }

}
