/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing View
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ViewTests
    {
        // TODO uncomment below to declare an instance variable for View
        //private View instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of View
            //instance = new View();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of View
        /// </summary>
        [Test]
        public void ViewInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" View
            //Assert.IsInstanceOfType<View> (instance, "variable 'instance' is a View");
        }


        /// <summary>
        /// Test the property 'AccessSids'
        /// </summary>
        [Test]
        public void AccessSidsTest()
        {
            // TODO unit test for the property 'AccessSids'
        }
        /// <summary>
        /// Test the property 'Aliases'
        /// </summary>
        [Test]
        public void AliasesTest()
        {
            // TODO unit test for the property 'Aliases'
        }
        /// <summary>
        /// Test the property 'AllSmbMountPaths'
        /// </summary>
        [Test]
        public void AllSmbMountPathsTest()
        {
            // TODO unit test for the property 'AllSmbMountPaths'
        }
        /// <summary>
        /// Test the property 'BasicMountPath'
        /// </summary>
        [Test]
        public void BasicMountPathTest()
        {
            // TODO unit test for the property 'BasicMountPath'
        }
        /// <summary>
        /// Test the property 'CaseInsensitiveNamesEnabled'
        /// </summary>
        [Test]
        public void CaseInsensitiveNamesEnabledTest()
        {
            // TODO unit test for the property 'CaseInsensitiveNamesEnabled'
        }
        /// <summary>
        /// Test the property 'CreateTimeMsecs'
        /// </summary>
        [Test]
        public void CreateTimeMsecsTest()
        {
            // TODO unit test for the property 'CreateTimeMsecs'
        }
        /// <summary>
        /// Test the property 'DataLockExpiryUsecs'
        /// </summary>
        [Test]
        public void DataLockExpiryUsecsTest()
        {
            // TODO unit test for the property 'DataLockExpiryUsecs'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EnableFilerAuditLogging'
        /// </summary>
        [Test]
        public void EnableFilerAuditLoggingTest()
        {
            // TODO unit test for the property 'EnableFilerAuditLogging'
        }
        /// <summary>
        /// Test the property 'EnableMixedModePermissions'
        /// </summary>
        [Test]
        public void EnableMixedModePermissionsTest()
        {
            // TODO unit test for the property 'EnableMixedModePermissions'
        }
        /// <summary>
        /// Test the property 'EnableSmbAccessBasedEnumeration'
        /// </summary>
        [Test]
        public void EnableSmbAccessBasedEnumerationTest()
        {
            // TODO unit test for the property 'EnableSmbAccessBasedEnumeration'
        }
        /// <summary>
        /// Test the property 'EnableSmbViewDiscovery'
        /// </summary>
        [Test]
        public void EnableSmbViewDiscoveryTest()
        {
            // TODO unit test for the property 'EnableSmbViewDiscovery'
        }
        /// <summary>
        /// Test the property 'FileExtensionFilter'
        /// </summary>
        [Test]
        public void FileExtensionFilterTest()
        {
            // TODO unit test for the property 'FileExtensionFilter'
        }
        /// <summary>
        /// Test the property 'LogicalQuota'
        /// </summary>
        [Test]
        public void LogicalQuotaTest()
        {
            // TODO unit test for the property 'LogicalQuota'
        }
        /// <summary>
        /// Test the property 'LogicalUsageBytes'
        /// </summary>
        [Test]
        public void LogicalUsageBytesTest()
        {
            // TODO unit test for the property 'LogicalUsageBytes'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NfsMountPath'
        /// </summary>
        [Test]
        public void NfsMountPathTest()
        {
            // TODO unit test for the property 'NfsMountPath'
        }
        /// <summary>
        /// Test the property 'ProtocolAccess'
        /// </summary>
        [Test]
        public void ProtocolAccessTest()
        {
            // TODO unit test for the property 'ProtocolAccess'
        }
        /// <summary>
        /// Test the property 'Qos'
        /// </summary>
        [Test]
        public void QosTest()
        {
            // TODO unit test for the property 'Qos'
        }
        /// <summary>
        /// Test the property 'SmbMountPath'
        /// </summary>
        [Test]
        public void SmbMountPathTest()
        {
            // TODO unit test for the property 'SmbMountPath'
        }
        /// <summary>
        /// Test the property 'SmbPermissionsInfo'
        /// </summary>
        [Test]
        public void SmbPermissionsInfoTest()
        {
            // TODO unit test for the property 'SmbPermissionsInfo'
        }
        /// <summary>
        /// Test the property 'StoragePolicyOverride'
        /// </summary>
        [Test]
        public void StoragePolicyOverrideTest()
        {
            // TODO unit test for the property 'StoragePolicyOverride'
        }
        /// <summary>
        /// Test the property 'SubnetWhitelist'
        /// </summary>
        [Test]
        public void SubnetWhitelistTest()
        {
            // TODO unit test for the property 'SubnetWhitelist'
        }
        /// <summary>
        /// Test the property 'ViewBoxId'
        /// </summary>
        [Test]
        public void ViewBoxIdTest()
        {
            // TODO unit test for the property 'ViewBoxId'
        }
        /// <summary>
        /// Test the property 'ViewBoxName'
        /// </summary>
        [Test]
        public void ViewBoxNameTest()
        {
            // TODO unit test for the property 'ViewBoxName'
        }
        /// <summary>
        /// Test the property 'ViewId'
        /// </summary>
        [Test]
        public void ViewIdTest()
        {
            // TODO unit test for the property 'ViewId'
        }
        /// <summary>
        /// Test the property 'ViewProtection'
        /// </summary>
        [Test]
        public void ViewProtectionTest()
        {
            // TODO unit test for the property 'ViewProtection'
        }

    }

}
