/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VmwareCloneParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VmwareCloneParametersTests
    {
        // TODO uncomment below to declare an instance variable for VmwareCloneParameters
        //private VmwareCloneParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VmwareCloneParameters
            //instance = new VmwareCloneParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VmwareCloneParameters
        /// </summary>
        [Test]
        public void VmwareCloneParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VmwareCloneParameters
            //Assert.IsInstanceOfType<VmwareCloneParameters> (instance, "variable 'instance' is a VmwareCloneParameters");
        }


        /// <summary>
        /// Test the property 'DatastoreFolderId'
        /// </summary>
        [Test]
        public void DatastoreFolderIdTest()
        {
            // TODO unit test for the property 'DatastoreFolderId'
        }
        /// <summary>
        /// Test the property 'DisableNetwork'
        /// </summary>
        [Test]
        public void DisableNetworkTest()
        {
            // TODO unit test for the property 'DisableNetwork'
        }
        /// <summary>
        /// Test the property 'NetworkId'
        /// </summary>
        [Test]
        public void NetworkIdTest()
        {
            // TODO unit test for the property 'NetworkId'
        }
        /// <summary>
        /// Test the property 'PoweredOn'
        /// </summary>
        [Test]
        public void PoweredOnTest()
        {
            // TODO unit test for the property 'PoweredOn'
        }
        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Test]
        public void PrefixTest()
        {
            // TODO unit test for the property 'Prefix'
        }
        /// <summary>
        /// Test the property 'ResourcePoolId'
        /// </summary>
        [Test]
        public void ResourcePoolIdTest()
        {
            // TODO unit test for the property 'ResourcePoolId'
        }
        /// <summary>
        /// Test the property 'Suffix'
        /// </summary>
        [Test]
        public void SuffixTest()
        {
            // TODO unit test for the property 'Suffix'
        }
        /// <summary>
        /// Test the property 'VmFolderId'
        /// </summary>
        [Test]
        public void VmFolderIdTest()
        {
            // TODO unit test for the property 'VmFolderId'
        }

    }

}
