/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Specifies job parameters applicable for all &#39;kHyperV&#39; Environment type Protection Sources in a Protection Job.
    /// </summary>
    [DataContract]
    public partial class HypervEnvJobParameters :  IEquatable<HypervEnvJobParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HypervEnvJobParameters" /> class.
        /// </summary>
        /// <param name="fallbackToCrashConsistent">If true, takes a crash-consistent snapshot when app-consistent snapshot fails. Otherwise, the snapshot attempt is marked failed. By default, this field is set to false..</param>
        public HypervEnvJobParameters(bool? fallbackToCrashConsistent = default(bool?))
        {
            this.FallbackToCrashConsistent = fallbackToCrashConsistent;
        }
        
        /// <summary>
        /// If true, takes a crash-consistent snapshot when app-consistent snapshot fails. Otherwise, the snapshot attempt is marked failed. By default, this field is set to false.
        /// </summary>
        /// <value>If true, takes a crash-consistent snapshot when app-consistent snapshot fails. Otherwise, the snapshot attempt is marked failed. By default, this field is set to false.</value>
        [DataMember(Name="fallbackToCrashConsistent", EmitDefaultValue=false)]
        public bool? FallbackToCrashConsistent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HypervEnvJobParameters {\n");
            sb.Append("  FallbackToCrashConsistent: ").Append(FallbackToCrashConsistent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HypervEnvJobParameters);
        }

        /// <summary>
        /// Returns true if HypervEnvJobParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of HypervEnvJobParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HypervEnvJobParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FallbackToCrashConsistent == input.FallbackToCrashConsistent ||
                    (this.FallbackToCrashConsistent != null &&
                    this.FallbackToCrashConsistent.Equals(input.FallbackToCrashConsistent))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FallbackToCrashConsistent != null)
                    hashCode = hashCode * 59 + this.FallbackToCrashConsistent.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
