/* 
 * Cohesity REST API
 *
 * This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStaticRouteApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List the Static Routes for the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the Static Routes for the Cohesity Cluster.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;StaticRoute&gt;</returns>
        List<StaticRoute> GetStaticRoutes ();

        /// <summary>
        /// List the Static Routes for the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the Static Routes for the Cohesity Cluster.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;StaticRoute&gt;</returns>
        ApiResponse<List<StaticRoute>> GetStaticRoutesWithHttpInfo ();
        /// <summary>
        /// Remove the specified Static Route from the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the delete status upon completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <returns></returns>
        void RemoveStaticRoute (string ip);

        /// <summary>
        /// Remove the specified Static Route from the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the delete status upon completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RemoveStaticRouteWithHttpInfo (string ip);
        /// <summary>
        /// Create or update a Static Route on the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the created or updated Static Route on the Cohesity Cluster.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>StaticRoute</returns>
        StaticRoute UpdateStaticRoute (string ip, StaticRoute body = null);

        /// <summary>
        /// Create or update a Static Route on the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the created or updated Static Route on the Cohesity Cluster.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of StaticRoute</returns>
        ApiResponse<StaticRoute> UpdateStaticRouteWithHttpInfo (string ip, StaticRoute body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// List the Static Routes for the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the Static Routes for the Cohesity Cluster.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;StaticRoute&gt;</returns>
        System.Threading.Tasks.Task<List<StaticRoute>> GetStaticRoutesAsync ();

        /// <summary>
        /// List the Static Routes for the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the Static Routes for the Cohesity Cluster.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;StaticRoute&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<StaticRoute>>> GetStaticRoutesAsyncWithHttpInfo ();
        /// <summary>
        /// Remove the specified Static Route from the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the delete status upon completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task RemoveStaticRouteAsync (string ip);

        /// <summary>
        /// Remove the specified Static Route from the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the delete status upon completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RemoveStaticRouteAsyncWithHttpInfo (string ip);
        /// <summary>
        /// Create or update a Static Route on the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the created or updated Static Route on the Cohesity Cluster.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of StaticRoute</returns>
        System.Threading.Tasks.Task<StaticRoute> UpdateStaticRouteAsync (string ip, StaticRoute body = null);

        /// <summary>
        /// Create or update a Static Route on the Cohesity Cluster.
        /// </summary>
        /// <remarks>
        /// Returns the created or updated Static Route on the Cohesity Cluster.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (StaticRoute)</returns>
        System.Threading.Tasks.Task<ApiResponse<StaticRoute>> UpdateStaticRouteAsyncWithHttpInfo (string ip, StaticRoute body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StaticRouteApi : IStaticRouteApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StaticRouteApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StaticRouteApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StaticRouteApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StaticRouteApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// List the Static Routes for the Cohesity Cluster. Returns the Static Routes for the Cohesity Cluster.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;StaticRoute&gt;</returns>
        public List<StaticRoute> GetStaticRoutes ()
        {
             ApiResponse<List<StaticRoute>> localVarResponse = GetStaticRoutesWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List the Static Routes for the Cohesity Cluster. Returns the Static Routes for the Cohesity Cluster.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;StaticRoute&gt;</returns>
        public ApiResponse< List<StaticRoute> > GetStaticRoutesWithHttpInfo ()
        {

            var localVarPath = "/public/staticRoutes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStaticRoutes", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<StaticRoute>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<StaticRoute>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<StaticRoute>)));
        }

        /// <summary>
        /// List the Static Routes for the Cohesity Cluster. Returns the Static Routes for the Cohesity Cluster.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;StaticRoute&gt;</returns>
        public async System.Threading.Tasks.Task<List<StaticRoute>> GetStaticRoutesAsync ()
        {
             ApiResponse<List<StaticRoute>> localVarResponse = await GetStaticRoutesAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List the Static Routes for the Cohesity Cluster. Returns the Static Routes for the Cohesity Cluster.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;StaticRoute&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<StaticRoute>>> GetStaticRoutesAsyncWithHttpInfo ()
        {

            var localVarPath = "/public/staticRoutes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStaticRoutes", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<StaticRoute>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<StaticRoute>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<StaticRoute>)));
        }

        /// <summary>
        /// Remove the specified Static Route from the Cohesity Cluster. Returns the delete status upon completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <returns></returns>
        public void RemoveStaticRoute (string ip)
        {
             RemoveStaticRouteWithHttpInfo(ip);
        }

        /// <summary>
        /// Remove the specified Static Route from the Cohesity Cluster. Returns the delete status upon completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> RemoveStaticRouteWithHttpInfo (string ip)
        {
            // verify the required parameter 'ip' is set
            if (ip == null)
                throw new ApiException(400, "Missing required parameter 'ip' when calling StaticRouteApi->RemoveStaticRoute");

            var localVarPath = "/public/staticRoutes/{ip}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ip != null) localVarPathParams.Add("ip", this.Configuration.ApiClient.ParameterToString(ip)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RemoveStaticRoute", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Remove the specified Static Route from the Cohesity Cluster. Returns the delete status upon completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RemoveStaticRouteAsync (string ip)
        {
             await RemoveStaticRouteAsyncWithHttpInfo(ip);

        }

        /// <summary>
        /// Remove the specified Static Route from the Cohesity Cluster. Returns the delete status upon completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> RemoveStaticRouteAsyncWithHttpInfo (string ip)
        {
            // verify the required parameter 'ip' is set
            if (ip == null)
                throw new ApiException(400, "Missing required parameter 'ip' when calling StaticRouteApi->RemoveStaticRoute");

            var localVarPath = "/public/staticRoutes/{ip}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ip != null) localVarPathParams.Add("ip", this.Configuration.ApiClient.ParameterToString(ip)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RemoveStaticRoute", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Create or update a Static Route on the Cohesity Cluster. Returns the created or updated Static Route on the Cohesity Cluster.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>StaticRoute</returns>
        public StaticRoute UpdateStaticRoute (string ip, StaticRoute body = null)
        {
             ApiResponse<StaticRoute> localVarResponse = UpdateStaticRouteWithHttpInfo(ip, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create or update a Static Route on the Cohesity Cluster. Returns the created or updated Static Route on the Cohesity Cluster.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of StaticRoute</returns>
        public ApiResponse< StaticRoute > UpdateStaticRouteWithHttpInfo (string ip, StaticRoute body = null)
        {
            // verify the required parameter 'ip' is set
            if (ip == null)
                throw new ApiException(400, "Missing required parameter 'ip' when calling StaticRouteApi->UpdateStaticRoute");

            var localVarPath = "/public/staticRoutes/{ip}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ip != null) localVarPathParams.Add("ip", this.Configuration.ApiClient.ParameterToString(ip)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateStaticRoute", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StaticRoute>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (StaticRoute) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StaticRoute)));
        }

        /// <summary>
        /// Create or update a Static Route on the Cohesity Cluster. Returns the created or updated Static Route on the Cohesity Cluster.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of StaticRoute</returns>
        public async System.Threading.Tasks.Task<StaticRoute> UpdateStaticRouteAsync (string ip, StaticRoute body = null)
        {
             ApiResponse<StaticRoute> localVarResponse = await UpdateStaticRouteAsyncWithHttpInfo(ip, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create or update a Static Route on the Cohesity Cluster. Returns the created or updated Static Route on the Cohesity Cluster.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ip">Specifies the subnet IP of the route destination network.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (StaticRoute)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StaticRoute>> UpdateStaticRouteAsyncWithHttpInfo (string ip, StaticRoute body = null)
        {
            // verify the required parameter 'ip' is set
            if (ip == null)
                throw new ApiException(400, "Missing required parameter 'ip' when calling StaticRouteApi->UpdateStaticRoute");

            var localVarPath = "/public/staticRoutes/{ip}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ip != null) localVarPathParams.Add("ip", this.Configuration.ApiClient.ParameterToString(ip)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateStaticRoute", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StaticRoute>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (StaticRoute) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StaticRoute)));
        }

    }
}
