// Copyright 2019 Cohesity Inc.

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Cohesity.Model
{
    /// <summary>
    /// Message to capture details about entities used for RDS Postgres workflows on DMaaS.
    /// </summary>
    [DataContract]
    public partial class AwsEntity :  IEquatable<AwsEntity>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwsEntity" /> class.
        /// </summary>
        /// <param name="displayName">Contains the name of the entity..</param>
        /// <param name="id">The id generated by magneto for the given entity. This is unique across one cluster..</param>
        public AwsEntity(string displayName = default(string), long? id = default(long?))
        {
            this.DisplayName = displayName;
            this.Id = id;
            this.DisplayName = displayName;
            this.Id = id;
        }
        
        /// <summary>
        /// Contains the name of the entity.
        /// </summary>
        /// <value>Contains the name of the entity.</value>
        [DataMember(Name="displayName", EmitDefaultValue=true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// The id generated by magneto for the given entity. This is unique across one cluster.
        /// </summary>
        /// <value>The id generated by magneto for the given entity. This is unique across one cluster.</value>
        [DataMember(Name="id", EmitDefaultValue=true)]
        public long? Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString() { return ToJson(); }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwsEntity);
        }

        /// <summary>
        /// Returns true if AwsEntity instances are equal
        /// </summary>
        /// <param name="input">Instance of AwsEntity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwsEntity input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                return hashCode;
            }
        }

    }

}

