// Copyright 2019 Cohesity Inc.

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Cohesity.Model
{
    /// <summary>
    /// Specifies the details of a certificate.
    /// </summary>
    [DataContract]
    public partial class CertificateObject :  IEquatable<CertificateObject>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CertificateObject" /> class.
        /// </summary>
        /// <param name="displayName">Display name of the certificate..</param>
        /// <param name="generatedBy">Certificate generated by. Currently it can be either External or Cohesity..</param>
        /// <param name="thumbprint">SHA1 thumbprint of the certificate..</param>
        public CertificateObject(string displayName = default(string), string generatedBy = default(string), string thumbprint = default(string))
        {
            this.DisplayName = displayName;
            this.GeneratedBy = generatedBy;
            this.Thumbprint = thumbprint;
            this.DisplayName = displayName;
            this.GeneratedBy = generatedBy;
            this.Thumbprint = thumbprint;
        }
        
        /// <summary>
        /// Display name of the certificate.
        /// </summary>
        /// <value>Display name of the certificate.</value>
        [DataMember(Name="displayName", EmitDefaultValue=true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Certificate generated by. Currently it can be either External or Cohesity.
        /// </summary>
        /// <value>Certificate generated by. Currently it can be either External or Cohesity.</value>
        [DataMember(Name="generatedBy", EmitDefaultValue=true)]
        public string GeneratedBy { get; set; }

        /// <summary>
        /// SHA1 thumbprint of the certificate.
        /// </summary>
        /// <value>SHA1 thumbprint of the certificate.</value>
        [DataMember(Name="thumbprint", EmitDefaultValue=true)]
        public string Thumbprint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString() { return ToJson(); }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CertificateObject);
        }

        /// <summary>
        /// Returns true if CertificateObject instances are equal
        /// </summary>
        /// <param name="input">Instance of CertificateObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CertificateObject input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.GeneratedBy == input.GeneratedBy ||
                    (this.GeneratedBy != null &&
                    this.GeneratedBy.Equals(input.GeneratedBy))
                ) && 
                (
                    this.Thumbprint == input.Thumbprint ||
                    (this.Thumbprint != null &&
                    this.Thumbprint.Equals(input.Thumbprint))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.GeneratedBy != null)
                    hashCode = hashCode * 59 + this.GeneratedBy.GetHashCode();
                if (this.Thumbprint != null)
                    hashCode = hashCode * 59 + this.Thumbprint.GetHashCode();
                return hashCode;
            }
        }

    }

}

