// Copyright 2019 Cohesity Inc.

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Cohesity.Model
{
    /// <summary>
    /// DeleteProtectionJobParam is the struct for deleting a protection job.
    /// </summary>
    [DataContract]
    public partial class DeleteProtectionJobParam :  IEquatable<DeleteProtectionJobParam>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteProtectionJobParam" /> class.
        /// </summary>
        /// <param name="deleteSnapshots">Specifies if Snapshots generated by the Protection Job should also be deleted when the Job is deleted..</param>
        /// <param name="reason">Specifies the reason for group deletion with or without snapshots.</param>
        public DeleteProtectionJobParam(bool? deleteSnapshots = default(bool?), string reason = default(string))
        {
            this.DeleteSnapshots = deleteSnapshots;
            this.Reason = reason;
            this.DeleteSnapshots = deleteSnapshots;
            this.Reason = reason;
        }
        
        /// <summary>
        /// Specifies if Snapshots generated by the Protection Job should also be deleted when the Job is deleted.
        /// </summary>
        /// <value>Specifies if Snapshots generated by the Protection Job should also be deleted when the Job is deleted.</value>
        [DataMember(Name="deleteSnapshots", EmitDefaultValue=true)]
        public bool? DeleteSnapshots { get; set; }

        /// <summary>
        /// Specifies the reason for group deletion with or without snapshots
        /// </summary>
        /// <value>Specifies the reason for group deletion with or without snapshots</value>
        [DataMember(Name="reason", EmitDefaultValue=true)]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString() { return ToJson(); }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DeleteProtectionJobParam);
        }

        /// <summary>
        /// Returns true if DeleteProtectionJobParam instances are equal
        /// </summary>
        /// <param name="input">Instance of DeleteProtectionJobParam to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeleteProtectionJobParam input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DeleteSnapshots == input.DeleteSnapshots ||
                    (this.DeleteSnapshots != null &&
                    this.DeleteSnapshots.Equals(input.DeleteSnapshots))
                ) && 
                (
                    this.Reason == input.Reason ||
                    (this.Reason != null &&
                    this.Reason.Equals(input.Reason))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DeleteSnapshots != null)
                    hashCode = hashCode * 59 + this.DeleteSnapshots.GetHashCode();
                if (this.Reason != null)
                    hashCode = hashCode * 59 + this.Reason.GetHashCode();
                return hashCode;
            }
        }

    }

}

