// Copyright 2019 Cohesity Inc.

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Cohesity.Model
{
    /// <summary>
    /// EntitiesExternalMetadata
    /// </summary>
    [DataContract]
    public partial class EntitiesExternalMetadata :  IEquatable<EntitiesExternalMetadata>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntitiesExternalMetadata" /> class.
        /// </summary>
        /// <param name="entityExternalMetadata">entityExternalMetadata.</param>
        /// <param name="entityId">Unique integer entity id generated by magneto for the given entity.</param>
        public EntitiesExternalMetadata(EntityExternalMetadataProto entityExternalMetadata = default(EntityExternalMetadataProto), long? entityId = default(long?))
        {
            this.EntityId = entityId;
            this.EntityExternalMetadata = entityExternalMetadata;
            this.EntityId = entityId;
        }
        
        /// <summary>
        /// Gets or Sets EntityExternalMetadata
        /// </summary>
        [DataMember(Name="entityExternalMetadata", EmitDefaultValue=false)]
        public EntityExternalMetadataProto EntityExternalMetadata { get; set; }

        /// <summary>
        /// Unique integer entity id generated by magneto for the given entity
        /// </summary>
        /// <value>Unique integer entity id generated by magneto for the given entity</value>
        [DataMember(Name="entityId", EmitDefaultValue=true)]
        public long? EntityId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString() { return ToJson(); }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EntitiesExternalMetadata);
        }

        /// <summary>
        /// Returns true if EntitiesExternalMetadata instances are equal
        /// </summary>
        /// <param name="input">Instance of EntitiesExternalMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EntitiesExternalMetadata input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EntityExternalMetadata == input.EntityExternalMetadata ||
                    (this.EntityExternalMetadata != null &&
                    this.EntityExternalMetadata.Equals(input.EntityExternalMetadata))
                ) && 
                (
                    this.EntityId == input.EntityId ||
                    (this.EntityId != null &&
                    this.EntityId.Equals(input.EntityId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EntityExternalMetadata != null)
                    hashCode = hashCode * 59 + this.EntityExternalMetadata.GetHashCode();
                if (this.EntityId != null)
                    hashCode = hashCode * 59 + this.EntityId.GetHashCode();
                return hashCode;
            }
        }

    }

}

