// Copyright 2019 Cohesity Inc.

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Cohesity.Model
{
    /// <summary>
    /// EntityIdProto
    /// </summary>
    [DataContract]
    public partial class EntityIdProto :  IEquatable<EntityIdProto>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntityIdProto" /> class.
        /// </summary>
        /// <param name="intId">Unique integer entity id generated by magneto for the given entity. This is unique across one cluster. Two different Cohesity clusters may have same int_id for two different entities..</param>
        /// <param name="stringIds">stringIds.</param>
        public EntityIdProto(long? intId = default(long?), StringEntityIdsProto stringIds = default(StringEntityIdsProto))
        {
            this.IntId = intId;
            this.IntId = intId;
            this.StringIds = stringIds;
        }
        
        /// <summary>
        /// Unique integer entity id generated by magneto for the given entity. This is unique across one cluster. Two different Cohesity clusters may have same int_id for two different entities.
        /// </summary>
        /// <value>Unique integer entity id generated by magneto for the given entity. This is unique across one cluster. Two different Cohesity clusters may have same int_id for two different entities.</value>
        [DataMember(Name="intId", EmitDefaultValue=true)]
        public long? IntId { get; set; }

        /// <summary>
        /// Gets or Sets StringIds
        /// </summary>
        [DataMember(Name="stringIds", EmitDefaultValue=false)]
        public StringEntityIdsProto StringIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString() { return ToJson(); }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EntityIdProto);
        }

        /// <summary>
        /// Returns true if EntityIdProto instances are equal
        /// </summary>
        /// <param name="input">Instance of EntityIdProto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EntityIdProto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IntId == input.IntId ||
                    (this.IntId != null &&
                    this.IntId.Equals(input.IntId))
                ) && 
                (
                    this.StringIds == input.StringIds ||
                    (this.StringIds != null &&
                    this.StringIds.Equals(input.StringIds))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IntId != null)
                    hashCode = hashCode * 59 + this.IntId.GetHashCode();
                if (this.StringIds != null)
                    hashCode = hashCode * 59 + this.StringIds.GetHashCode();
                return hashCode;
            }
        }

    }

}

