// Copyright 2018 Cohesity Inc.

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace Cohesity.Models
{
    /// <summary>
    /// MapperInfo
    /// </summary>
    [DataContract]
    public partial class MapperInfo :  IEquatable<MapperInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MapperInfo" /> class.
        /// </summary>
        /// <param name="code">The code of the mapper in the specified language. Should be UTF-8..</param>
        /// <param name="id">Mapper ID generated by system. Absent when user is creating a new mapper. Mandatory in all other use cases..</param>
        /// <param name="isSystemDefined">Whether the mapper is system defined..</param>
        /// <param name="jarName">User can write their own mapper/reducer or upload jar files containing mappers and reducers. If this mapper was part of a jar file, then this field will have the JAR name..</param>
        /// <param name="jarPath">path of JAR in which this mapper was found. This is applicable only when this mapper was uploaded via JAR. TODO(apurv): This is not immune to viewbox name change. Please write a proto to capture paths that are immune to this..</param>
        /// <param name="language">Language of the mapper..</param>
        /// <param name="name">Name of the mapper..</param>
        public MapperInfo(string code = default(string), long? id = default(long?), bool? isSystemDefined = default(bool?), string jarName = default(string), string jarPath = default(string), int? language = default(int?), string name = default(string))
        {
            this.Code = code;
            this.Id = id;
            this.IsSystemDefined = isSystemDefined;
            this.JarName = jarName;
            this.JarPath = jarPath;
            this.Language = language;
            this.Name = name;
        }
        
        /// <summary>
        /// The code of the mapper in the specified language. Should be UTF-8.
        /// </summary>
        /// <value>The code of the mapper in the specified language. Should be UTF-8.</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Mapper ID generated by system. Absent when user is creating a new mapper. Mandatory in all other use cases.
        /// </summary>
        /// <value>Mapper ID generated by system. Absent when user is creating a new mapper. Mandatory in all other use cases.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Whether the mapper is system defined.
        /// </summary>
        /// <value>Whether the mapper is system defined.</value>
        [DataMember(Name="isSystemDefined", EmitDefaultValue=false)]
        public bool? IsSystemDefined { get; set; }

        /// <summary>
        /// User can write their own mapper/reducer or upload jar files containing mappers and reducers. If this mapper was part of a jar file, then this field will have the JAR name.
        /// </summary>
        /// <value>User can write their own mapper/reducer or upload jar files containing mappers and reducers. If this mapper was part of a jar file, then this field will have the JAR name.</value>
        [DataMember(Name="jarName", EmitDefaultValue=false)]
        public string JarName { get; set; }

        /// <summary>
        /// path of JAR in which this mapper was found. This is applicable only when this mapper was uploaded via JAR. TODO(apurv): This is not immune to viewbox name change. Please write a proto to capture paths that are immune to this.
        /// </summary>
        /// <value>path of JAR in which this mapper was found. This is applicable only when this mapper was uploaded via JAR. TODO(apurv): This is not immune to viewbox name change. Please write a proto to capture paths that are immune to this.</value>
        [DataMember(Name="jarPath", EmitDefaultValue=false)]
        public string JarPath { get; set; }

        /// <summary>
        /// Language of the mapper.
        /// </summary>
        /// <value>Language of the mapper.</value>
        [DataMember(Name="language", EmitDefaultValue=false)]
        public int? Language { get; set; }

        /// <summary>
        /// Name of the mapper.
        /// </summary>
        /// <value>Name of the mapper.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return ToJson();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MapperInfo);
        }

        /// <summary>
        /// Returns true if MapperInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of MapperInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MapperInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.IsSystemDefined == input.IsSystemDefined ||
                    (this.IsSystemDefined != null &&
                    this.IsSystemDefined.Equals(input.IsSystemDefined))
                ) && 
                (
                    this.JarName == input.JarName ||
                    (this.JarName != null &&
                    this.JarName.Equals(input.JarName))
                ) && 
                (
                    this.JarPath == input.JarPath ||
                    (this.JarPath != null &&
                    this.JarPath.Equals(input.JarPath))
                ) && 
                (
                    this.Language == input.Language ||
                    (this.Language != null &&
                    this.Language.Equals(input.Language))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.IsSystemDefined != null)
                    hashCode = hashCode * 59 + this.IsSystemDefined.GetHashCode();
                if (this.JarName != null)
                    hashCode = hashCode * 59 + this.JarName.GetHashCode();
                if (this.JarPath != null)
                    hashCode = hashCode * 59 + this.JarPath.GetHashCode();
                if (this.Language != null)
                    hashCode = hashCode * 59 + this.Language.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }

        
    }

}

